---
title: "ntw 2025 data viz"
date: "2025-12-01"
---

# # preamble & loading

data viz for ntw 2025

```{r load libraries and utils}
here::i_am("_ntw/scripts/analysis/viz-tents.Rmd")
library(here)

library(tidyverse)
library(patchwork) # for plot_layout
# library(survival) # for fitting surv
# library(survminer) # for plotting surv

source(here("_ntw/scripts/utils/analysis.R"))
source(here("_ntw/scripts/utils/analysis-viz.R"))
```

```{r load data, message = FALSE, warning=FALSE}
source(here("_ntw/scripts/R/wrangle-tents.R"))

# convert things into factors for ease of graphing
dfs_tents <- dfs_tents %>%
    lapply(., \(x){
    x %>%
      ungroup() %>%
      mutate(across(c("year", "mate.trt", starts_with("trt")), as.factor),
             mate.type = factor(mate.type, 
                                levels = c("within", "between")))
  })
```

# # diagnostic plots

## dist eggs laid per f

```{r}
hist(dfs_tents$n_pertent$n.coll.perf)
mean(dfs_tents$n_pertent$n.coll.perf, na.rm = TRUE)
```

## dist eggs hatched (raw)

- distribution is mega bad. use a ZIP/ZINB model?

```{r}
hist(dfs_tents$n_pertent$n.hatch)
# 17/77 tents w hatchlings (both yrs)

# per yr
dfs_tents$n_pertent %>%
  #filter(year == 2025) %>%
  ggplot(aes(x = n.hatch, fill = as.factor(year))) +
  geom_bar()
```


# # final

## hatch+laid btwn yrs 

```{r}
# both yrs
dfs_tents$ss_nocol %>%
  FilterForLabEggs() %>%
  ggplot(aes(y = p.hatch, x = n.total.coll, 
             col = mate.trt, shape = mate.hs)) +
  geom_point() +
  geom_errorbar(aes(ymax = p.hatch + se.hatch,
                    ymin = p.hatch - se.hatch),
                width = 100) +
  # x err bar is too small to notice for 2025
  facet_wrap(mate.type ~ year) +
  #labs(x = "total eggs collected") +
  scale_color_brewer(palette = "Dark2")
```

```{r}
# sep years
.plotfn <- function(x){
  x %>%
    FilterForLabEggs() %>%
        mutate(mate.hs = case_when(mate.hs == "both" ~ "*F + *M",
                               mate.hs == "f" ~ "*F + M",
                               mate.hs == "m" ~ "F + *M")) %>%
    ggplot(aes(y = p.hatch, x = n.total.coll,
               col = mate.trt, shape = mate.hs)) +
    geom_point(size = 2) +
    geom_errorbar(aes(ymax = p.hatch + se.hatch,
                      ymin = p.hatch - se.hatch),
                  width = CalcErrWd(x = dfs_tents$ss_nocol$n.total.coll, 
                                    pct = 0.05)) +
    # x err bar is too small to notice so omit
    geom_text(aes(label = n.f.total),
              hjust = 1.25, vjust = -1.3,
              show.legend = FALSE) + 
    #scale_color_brewer(palette = "Dark2") +
    labs(col = "treatment",
         shape = "treated sex",
         y = "proportion hatched",
         x = "eggs laid") +
    scale_color_manual(values = c("#00A3B6", "#4B1D91", "#A71B4B", "#F9A92E")) +
    facet_wrap(~ mate.type, labeller = as_labeller(c(`within` = "overall trt effects", 
                                                     `between` = "sex-specific effects"))) +
    ylim(c(0, 0.305))
}

dfs_tents$ss_nocol %>%
  filter(year == 2023) %>%
  .plotfn() +
  labs(caption = "2023; N = # females") 

dfs_tents$ss_nocol %>%
  filter(year == 2025) %>%
  .plotfn() +
  labs(caption = "2025; N = # females")
```

## hatch+laid effect of col bugs in 2025
```{r}
## testing effect of including the col or not for 2025
.plotfn <- function(x){
  x %>%
   FilterForLabEggs() %>%
    ### SPECIFIC FOR THESE PLOTS ###
    filter(mate.type == "within",
           #mate.trt == 260
           ) %>%
    ###############################
   ggplot(aes(y = p.hatch, x = n.total.coll,
             col = mate.trt, 
             shape = mate.col
             )) +
  geom_point(size = 2) +
    geom_text(aes(label = n.f.total),
            hjust = 1.25, vjust = -1.3, show.legend = FALSE) + 
  geom_errorbar(aes(ymax = p.hatch + se.hatch,
                    ymin = p.hatch - se.hatch),
                width = CalcErrWd(x = dfs_tents$ss_nocol$n.total.coll,
                                  pct = 0.025)
                ) +
  facet_wrap(~mate.type) +
    scale_color_brewer(palette = "Dark2") +
    #ylim(c(0, 0.58)) + #### to keep axes same for these plots
    labs(shape = "sex of col bug")
}

p1 <- 
  dfs_tents$ss_nocol %>%
  mutate(mate.col = "na") %>%
  filter(year == "2025") %>%
  .plotfn() +
  labs(caption = "mate.type and mate.pop = lab for col") +
  scale_shape_manual(values = 16) +
  guides(shape = "none")

p2 <- 
dfs_tents$ss_matecol %>%
  mutate(mate.col = replace_na(mate.col, "na")) %>%
  filter(year == "2025") %>%
  .plotfn() +
  labs(caption = "mate.type = col") +
  scale_shape_manual(values = c(17, 15, 16)) +
  guides(shape = "none")

p3 <- 
dfs_tents$ss_allcol %>%
  mutate(mate.col = replace_na(mate.col, "na")) %>%
  filter(year == "2025") %>%
  .plotfn() +
  labs(caption = "mate.type and mate.pop for\nlab/col are distinct") +
  scale_shape_manual(values = c(3, 17, 15, 16))

p1
p2
p3
```
```{r}
# patchworking...
(p1 + p2 + p3) +
  plot_layout(guides = "collect", axes = "collect",
              #ncol = 1, nrow = 3, widths = c(1:2)
              ) &
  #guides(col = guide_legend(nrow = 2, byrow = TRUE)) &
  ylim(c(0, 0.58)) &
  theme(legend.position = "top", #legend.box = "vertical",
        legend.margin = margin()) &
  
  plot_annotation(title = "effect of parsing col ctrls") 

```

## eggs laid

### facet by year
```{r}
.plotfn <- function(x){
  x %>%
    FilterForLabEggs() %>% 
    # mutate(mate.hs = case_when(mate.hs == "both" ~ "*F + *M",
    #                            mate.hs == "f" ~ "*F + M",
    #                            mate.hs == "m" ~ "F + *M")) %>%
    ggplot(aes(#y = avg.coll.perf, 
      y = avg.sqrt.coll.perf,
      x = mate.trt,
      lty = mate.hs, shape = mate.hs,
      group = mate.hs,
      col = mate.hs
      # shape = mate.hs, lty = mate.type,
      # group = interaction(mate.hs, mate.type)
    )) + 
    # very overwhelming w error bars lol
    # geom_errorbar(aes(ymax = avg.coll.perf + se.coll.perf,
    #                   ymin = avg.coll.perf - se.coll.perf,),
    #               lty = "solid", width = 0.5) +
    # geom_errorbar(aes(ymax = avg.sqrt.coll.perf + se.sqrt.coll.perf,
    #                   ymin = avg.sqrt.coll.perf - se.sqrt.coll.perf),
    #               lty = "solid", width = 0.5) +
    geom_text(aes(label = n.f.total),
              vjust = -0.5, hjust = -0.5, position = "jitter",
              show.legend = FALSE) +
    # geom_text(aes(label = paste0(n.cages.total, "C, ", n.f.total, "F")),
    #           vjust = -0.5, hjust = -0.5, #position = "jitter",
    #           show.legend = FALSE
    #           ) +
    geom_point(size=2) + geom_line() +
    facet_grid(~year) +
    theme_bw() +
    #scale_shape_manual(values = c(2, 0, 16)) +
    #scale_color_brewer(palette = "Dark2") +
    scale_color_manual(values = c("slateblue2", "maroon2", "deepskyblue")) +
    #scale_linetype_manual(values = c(3, 2, 1)) +
    labs(col = "treated sex", lty = "treated sex", shape = "treated sex",
         caption = "mean±se; lab only; N = # F",
         y = "sqrt [eggs laid per female]", x = "treatment")
}

# connect "btwn" trts to 26-26
.plotfn2 <- function(x){
    list(
      geom_line(data = x %>%
                  #FilterForLabEggs(dfs_tents$ss_nocol) %>%
                  filter(trt.f %in% c(260, 419), mate.hs %in% c("both", "f"),
                         trt.m != 419) %>%
                  select(-mate.trt) %>%
                  rename(mate.trt = trt.f) %>% mutate(mate.hs = "f",
                                                      #mate.hs = "*F + M"
                                                      ), #%>% View()
                #, color = "black"
                #, aes(group = mate.hs), 
                show.legend = FALSE
                ),
        geom_line(data = x %>%
                    #FilterForLabEggs(dfs_tents$ss_nocol) %>%
                    filter(trt.m %in% c(260, 419), mate.hs %in% c("both", "m"),
                           trt.f != 419) %>%
                    select(-mate.trt) %>%
                    rename(mate.trt = trt.m) %>% mutate(mate.hs = "m",
                                                        #mate.hs = "F + *M"
                                                        ) #%>% View()
                  ,
                  #aes(group = mate.trt), 
                  show.legend = FALSE
                  )
      )
}

dfs_tents$ss_nocol %>%
  .plotfn() +
  .plotfn2(FilterForLabEggs(dfs_tents$ss_nocol)) +
  scale_x_discrete(labels = c(p_labs$temps))

dfs_tents$ss_nocol %>%
  filter(mate.trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c(p_labs$temps))
  
```

### facet by sex v1

```{r}
.plotfn <- function(x){
  x %>%
    FilterForLabEggs() %>%
    ggplot(aes(y = avg.sqrt.coll.perf, x = mate.trt,
               group = interaction(year, mate.hs),
    )) +
    geom_point(#aes(size = n.f.total) # this looks dumb
      size = 2
    ) + 
    geom_line() +
    geom_errorbar(aes(ymax = avg.sqrt.coll.perf + se.sqrt.coll.perf,
                      ymin = avg.sqrt.coll.perf - se.sqrt.coll.perf),
                  width = 0.25, lty = "solid", show.legend = FALSE) +
    geom_text(aes(label = n.f.total), size = 3.5,
              hjust = -0.5, vjust = -0.7, show.legend = FALSE) +
    facet_wrap(~mate.hs, scales = "free_x",
               labeller = as_labeller(c(`both` = "F + M treated",
                                        `f` = "F treated",
                                        `m` = "M treated"))) +
    labs(y = "sqrt[eggs laid per f]",
         x = "temperature treatment",
         caption = "mean±se; N = # females") +
    # flavor 2
    #     scale_color_discrete(labels = c("within" = "to same trt", "between" = "to ctrl")) +
    # scale_linetype_discrete(labels = c("within" = "to same trt", "between" = "to ctrl")) +
    scale_x_discrete(labels = c(p_labs$temps))
}

# separate ctrl from expt
dfs_tents$ss_nocol%>%
  mutate(to.ctrl = case_when(mate.trt == "260" | mate.type == "between" ~ "mated to ctrl",
                             TRUE ~ "mated to expt")) %>%
  .plotfn() +
  # flavor 1
  aes(col = year, lty = year, shape = to.ctrl) +
  labs(shape = "mate type") +
  scale_shape_manual(values = c(1, 19))
  # flavor 2
  # aes(col = mate.type, lty = mate.type, shape = year) +
  # scale_shape_manual(values = c(19, 1))


# separate sexes
dfs_tents$ss_nocol %>%
  mutate(mate.hs2 = case_when(mate.hs == "both" ~ "both sexes",
                              TRUE ~ "one sex")) %>%
  .plotfn() +
  # flavor 1
  aes(col = year, lty = year, shape = mate.hs2) +
  labs(shape = "sexes treated?") +
   scale_shape_manual(values = c(19, 1))
  # flavor 2
  #aes(col = mate.type, lty = mate.type, shape = year)
```
### facet by sex v2
```{r}
.plotfn <- function(x){
  x %>%
    FilterForLabEggs() %>%
    mutate(mate.type = case_when(mate.type == "between" ~ "expt",
                                 TRUE ~ "ctrl"),
           trt.type = case_when(mate.trt == 260 ~ "ctrl",
                                TRUE ~ "expt")) %>%
    ggplot(aes(y = avg.sqrt.coll.perf, x = mate.trt,
               group = interaction(mate.type, year),
               col = mate.type,
               shape = year,
               lty = mate.type)) +
    geom_point(size = 2) +
    geom_line() +
    geom_errorbar(aes(ymax = avg.sqrt.coll.perf + se.sqrt.coll.perf,
                      ymin = avg.sqrt.coll.perf - se.sqrt.coll.perf),
                  width = 0.1, lty = "solid", show.legend = FALSE) +
    scale_shape_manual(values = c(19, 1)) +
    scale_color_brewer(palette = "Dark2") +
    scale_x_discrete(labels = p_labs$temps) +
    labs(y = "sqrt[eggs laid per f]",
         x = "experimental trt",
         lty = "mated to?",
         col = "mated to?")
}

p1 <- dfs_tents$ss_nocol %>%
  filter(mate.trt == 260) %>%
  .plotfn() +
  #scale_shape_manual(values = c(24, 25)) +
  facet_wrap(~trt.type, labeller = as_labeller(c(`ctrl` = "ctrl F + ctrl M"))) +
  guides(lty = "none", shape = "none", col = "none")

p2 <- dfs_tents$ss_nocol %>%
  filter(mate.trt != 260,
         mate.hs %in% c("f", "both")) %>%
  .plotfn() +
  facet_wrap(~trt.type, labeller = as_labeller(c(`expt` = "expt F + M")))

p3 <- dfs_tents$ss_nocol %>%
  filter(mate.trt != 260,
         mate.hs %in% c("m", "both")) %>%
  .plotfn() +
  facet_wrap(~trt.type, labeller = as_labeller(c(`expt` = "expt M + F")))

(p1 + p2 + p3) +
  plot_layout(guides = "collect", 
              axes = "collect") &
  ylim(c(0, 18))

```
### facet by sex v3
```{r}
.plotfn <- function(x){
  x %>%
    FilterForLabEggs() %>%
    mutate(mate.type = case_when(mate.type == "within" ~ "to expt",
                                 TRUE ~ "to ctrl"),
           facetlab = "label") %>%
    ggplot(aes(y = avg.sqrt.coll.perf, x = mate.trt,
               group = interaction(year, mate.type),
               shape = year,
               lty = mate.type, col = mate.type)) +
    geom_point(size = 2) +
    geom_line() +
    geom_errorbar(aes(ymax = avg.sqrt.coll.perf + se.sqrt.coll.perf,
                      ymin = avg.sqrt.coll.perf - se.sqrt.coll.perf),
                  width = 0.2, lty = "solid", show.legend = FALSE) +
    # messy to add numbers..
    # geom_text(aes(label = n.f.total), size = 3.5,
    #           hjust = -0.5, vjust = -0.7, show.legend = FALSE) +
    scale_shape_manual(values = c(19, 1)) +
    scale_color_hue(direction = -1) +
    scale_x_discrete(labels = p_labs$temps) +
        #theme(axis.title = element_blank()) +
    labs(y = "sqrt[eggs laid per f]",
       x = "temperature treatment",
       lty = "exptal matings", col = "exptal matings")
}

p1 <- dfs_tents$ss_nocol %>%
  filter(mate.trt == 260,
         mate.hs == "both") %>%
  mutate(mate.type = "ctrl to ctrl") %>% 
  .plotfn() +
  scale_color_manual(values = "#00BFC4") +
  guides(col = "none", lty = "none", 
         shape = "none") +
  facet_wrap(~facetlab, labeller = as_labeller(c(`label` = "ctrl F + ctrl M")), ncol = 1)

p2 <- dfs_tents$ss_nocol %>%
  filter(mate.trt != 260,
         mate.hs %in% c("f", "both")) %>%
  .plotfn() +
  facet_wrap(~facetlab, labeller = as_labeller(c(`label` = "expt F + ?")), ncol = 1)

p3 <- dfs_tents$ss_nocol %>%
  filter(mate.trt != 260,
         mate.hs %in% c("m", "both")) %>%
  .plotfn() +
  facet_wrap(~facetlab, labeller = as_labeller(c(`label` = "expt M + ?")), ncol = 1)
 
(p1 + p2 + p3) +
  plot_layout(guides = "collect", axes = "collect",
              widths = c(1, 2, 2)
              #design = "ABC"
              ) &
  ylim(c(0, 18)) 
  # labs(y = "sqrt[eggs laid per f]",
  #      x = "temperature treatment") &
  #plot_annotation(caption = "'expt' trt = 40-X") # i give up dude i think the facets are breaking it

```




## eggs hatched

### facet by year (overall)

```{r}
.plotfn <- function(x){
  x %>%
    FilterForLabEggs() %>% 
    # check if matches w .plotfn2
    # mutate(mate.hs = case_when(mate.hs == "both" ~ "*F + *M",
    #                            mate.hs == "f" ~ "*F + M",
    #                            mate.hs == "m" ~ "F + *M")) %>%
    ggplot(aes(y = p.hatch,
               x = mate.trt,
               lty = mate.hs, shape = mate.hs,
               group = mate.hs,
               col = mate.hs,)) + 
    geom_errorbar(aes(ymax = p.hatch + se.hatch,
                      ymin = p.hatch - se.hatch,),
                  lty = "solid", width = 0.25, show.legend = FALSE) +
    # geom_text(aes(label = n.total.coll),
    #           vjust = -0.5, hjust = -0.5, position = "jitter",
    #           show.legend = FALSE) +
    # geom_text(aes(label = paste0(n.cages.total, "C,", n.f.total, "F")),
    #       vjust = -0.5, hjust = -0.5, size = 3
    #       #position = "jitter"
    #       ) +
    #geom_point(aes(size=sqrt(n.total.coll))) + # looks dumb
    geom_point(size = 2) +
    geom_line() +
    facet_grid(~year) +
    theme_bw() +
    #scale_shape_manual(values = c(2, 0, 16)) +
    #scale_color_brewer(palette = "Dark2") +
    scale_color_manual(values = c("slateblue2", "maroon2", "deepskyblue")) +
    #scale_linetype_manual(values = c(3, 2, 1)) +
    labs(col = "treated sex", lty = "treated sex", shape = "treated sex",
         caption = "lab only; overall hatch prop. per mating combination",
         y = "proportion eggs hatched", x = "treatment")
}
.plotfn2 <- function(x){
    list(
      geom_line(data = x %>%
                  #FilterForLabEggs(dfs_tents$ss_nocol) %>%
                  filter(trt.f %in% c(260, 419), 
                         mate.hs %in% c("both", "f"),
                         trt.m != 419) %>%
                  select(-mate.trt) %>% 
                  rename(mate.trt = trt.f) %>% mutate(mate.hs = "f",
                                                      #mate.hs = "*F + M"
                                                      ) #%>% View()
                #, color = "black"
                , #aes(group = mate.hs), 
                show.legend = FALSE,
                ),
        geom_line(data = x %>%
                    #FilterForLabEggs(dfs_tents$ss_nocol) %>%
                    filter(trt.m %in% c(260, 419), mate.hs %in% c("both", "m"),
                           trt.f != 419) %>%
                    select(-mate.trt) %>%
                    rename(mate.trt = trt.m) %>% mutate(mate.hs = "m",
                                                        #mate.hs = "F + *M"
                                                        ) #%>% View()
                  ,
                  #aes(group = mate.trt), 
                  show.legend = FALSE
                  )
      )
}

dfs_tents$ss_nocol %>%
  .plotfn() +
  .plotfn2(FilterForLabEggs(dfs_tents$ss_nocol)) +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_tents$ss_nocol %>%
  filter(mate.trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))
```
### facet by sex (overall)

```{r}
.plotfn <- function(x){
  x %>%
    FilterForLabEggs() %>%
    mutate(mate.type = case_when(mate.type == "within" ~ "to expt",
                                 TRUE ~ "to ctrl"),
           facetlab = "label") %>%
    ggplot(aes(y = p.hatch, x = mate.trt,
               group = interaction(year, mate.type),
               shape = year,
               lty = mate.type, col = mate.type)) +
    geom_point(aes(size = sqrt(n.total.coll))) +
    geom_line() +
    geom_errorbar(aes(ymax = p.hatch + se.hatch,
                      ymin = p.hatch - se.hatch),
                  width = 0.2, lty = "solid", show.legend = FALSE) +
    # messy to add numbers..
    # geom_text(aes(label = n.f.total), size = 3.5,
    #           hjust = -0.5, vjust = -0.7, show.legend = FALSE) +
    scale_shape_manual(values = c(19, 1)) +
    scale_color_hue(direction = -1) +
    scale_x_discrete(labels = p_labs$temps) +
        #theme(axis.title = element_blank()) +
    labs(y = "prop. hatch per mate combo",
       x = "temperature treatment",
       lty = "exptal matings", col = "exptal matings")
}

p1 <- dfs_tents$ss_nocol %>%
  filter(mate.trt == 260,
         mate.hs == "both") %>%
  mutate(mate.type = "ctrl to ctrl") %>% 
  .plotfn() +
  scale_color_manual(values = "#00BFC4") +
  guides(col = "none", lty = "none", 
         shape = "none", size = "none") +
  facet_wrap(~facetlab, labeller = as_labeller(c(`label` = "ctrl F + ctrl M")), ncol = 1)

p2 <- dfs_tents$ss_nocol %>%
  filter(mate.trt != 260,
         mate.hs %in% c("f", "both")) %>%
  .plotfn() +
  guides(size = "none") +
  facet_wrap(~facetlab, labeller = as_labeller(c(`label` = "expt F + ?")), ncol = 1)

p3 <- dfs_tents$ss_nocol %>%
  filter(mate.trt != 260,
         mate.hs %in% c("m", "both")) %>%
  .plotfn() +
  facet_wrap(~facetlab, labeller = as_labeller(c(`label` = "expt M + ?")), ncol = 1)
 
(p1 + p2 + p3) +
  plot_layout(guides = "collect", axes = "collect",
              widths = c(1, 2, 2)
              #design = "ABC"
              ) &
  ylim(c(-0, 0.3))
  # labs(y = "sqrt[eggs laid per f]",
  #      x = "temperature treatment") &
  #plot_annotation(caption = "'expt' trt = 40-X") # i give up dude i think the facets are breaking it

```


### facet by sex (per cage)

```{r}
# not using hatch.perf bc i feel like its more about the # eggs than the # f
.plotfn <- function(x){
  x %>%
    FilterForLabEggs() %>%
    filter(avg.p.hatch.perc > 0) %>% # cleaner...
    mutate(mate.type = case_when(mate.type == "within" ~ "to expt",
                                 TRUE ~ "to ctrl"),
           facetlab = "label") %>%
    ggplot(aes(y = avg.p.hatch.perc, x = mate.trt,
               group = interaction(year, mate.type),
               shape = year,
               lty = mate.type, col = mate.type)) +
    geom_point(size = 2) +
    geom_line() +
    geom_errorbar(aes(ymax = avg.p.hatch.perc + se.p.hatch.perc,
                      ymin = avg.p.hatch.perc - se.p.hatch.perc),
                  width = 0.2, lty = "solid", show.legend = FALSE) +
    # messy to add numbers..
    geom_text(aes(label = n.cages.total), size = 3.5,
              hjust = -0.5, vjust = -0.7, show.legend = FALSE) +
    scale_shape_manual(values = c(19, 1)) +
    scale_color_hue(direction = -1) +
    scale_x_discrete(labels = p_labs$temps) +
        #theme(axis.title = element_blank()) +
    labs(y = "prop. hatch per cage",
       x = "temperature treatment",
       lty = "exptal matings", col = "exptal matings")
}

p1 <- dfs_tents$ss_nocol %>%
  filter(mate.trt == 260,
         mate.hs == "both") %>% 
  mutate(mate.type = "ctrl to ctrl") %>% 
  .plotfn() +
  scale_color_manual(values = "#00BFC4") +
  guides(col = "none", lty = "none", 
         shape = "none") +
  facet_wrap(~facetlab, labeller = as_labeller(c(`label` = "ctrl F + ctrl M")), ncol = 1)

p2 <- dfs_tents$ss_nocol %>%
  filter(mate.trt != 260,
         mate.hs %in% c("f", "both")) %>%
  .plotfn() +
  facet_wrap(~facetlab, labeller = as_labeller(c(`label` = "expt F + ?")), ncol = 1)

p3 <- dfs_tents$ss_nocol %>%
  filter(mate.trt != 260,
         mate.hs %in% c("m", "both")) %>%
  .plotfn() +
  facet_wrap(~facetlab, labeller = as_labeller(c(`label` = "expt M + ?")), ncol = 1)
 
(p1 + p2 + p3) +
  plot_layout(guides = "collect", axes = "collect",
              widths = c(1, 2, 2)
              #design = "ABC"
              ) &
  ylim(c(-0.15, 0.4))
  # labs(y = "sqrt[eggs laid per f]",
  #      x = "temperature treatment") &
  #plot_annotation(caption = "'expt' trt = 40-X") # i give up dude i think the facets are breaking it

```
