---
title: "ntw 2025 data viz"
date: "2025-12-01"
---

# # preamble & loading

data viz for ntw 2025

```{r set pathfinding}
here::i_am("_ntw/scripts/analysis/viz-dev.Rmd")
library(here)
```

```{r load libraries and utils}
library(tidyverse)
library(patchwork) # for plot_layout
# library(survival) # for fitting surv
# library(survminer) # for plotting surv

source(here("_ntw/scripts/utils/analysis.R"))
source(here("_ntw/scripts/utils/analysis-viz.R"))
```

```{r load data, message = FALSE, warning=FALSE}
source(here("_ntw/scripts/R/wrangle-dev.R"))

# convert things into factors for ease of graphing
dfs_dev_ss <- dfs_dev_ss %>%
    lapply(., \(x){
    x %>%
      ungroup() %>%
      mutate(across(c("year", "trt"), as.factor))
  })
```

# # overall dev

## survival to pup
```{r}
.plotfn <- function(x){
  x %>%
  FilterOutLabTB() %>%
  ggplot(aes(y = prop.pup,
             x = trt,
             col = year, #lty = year,
             group = year
             )) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymax = prop.pup + se.pup,
                    ymin = prop.pup - se.pup),
                width = 0.25, lty = "solid", show.legend = FALSE) +
  # geom_text(aes(label = n),
  #           hjust = -0.2, vjust = -.2,
  #           show.legend = FALSE) +
  facet_wrap(~pop) +
  labs(y = "% survived to pupation",
       x = "treatment",
       col = "year", #lty = "year"
       ) +
  scale_color_brewer(palette = "Dark2") +
  theme_bw()
}

dfs_dev_ss$surv_outcomes %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_dev_ss$surv_outcomes %>%
  filter(trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("19", "26", "33")) +
  labs(x = "minimum T (°C)")

```

## pup mass

```{r}
# sexes combined
.plotfn <- function(x){
  x %>%
      FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
  ggplot(aes(y = avg.mass, x = trt,
             #lty = year, 
             col = year,
             group = year,
             ))+
  geom_point() + geom_line() +
  geom_errorbar(aes(ymax = avg.mass + se.mass, 
                    ymin = avg.mass - se.mass),
                width = 0.3, lty = "solid") +
  # geom_text(aes(label = n),
  #           vjust = -0.2, hjust = -0.3,
  #           show.legend = FALSE) +
  facet_grid(~pop) +
  labs(y = "pupal mass (g)",
       caption = "mean±se; combined sexes") +
  scale_color_brewer(palette = "Dark2") +
  theme_bw()
}


dfs_dev_ss$ad_dev%>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev%>%
  filter(trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))
```

```{r}
# sexes parsed
# 2x2 pop + sex (better)

.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
    ggplot(aes(y = avg.mass, x = trt,
             col = year,
             group = interaction(year)
             )) +
  geom_point() + geom_line() +
    # geom_text(aes(label = n),
  #           vjust = -0.5, hjust = -0.5, size = 3.5,
  #           position = position_jitter(width = 0.2, height = 0.3, seed = 1),
  #           show.legend = FALSE) + # too busy
    geom_errorbar(aes(ymax = avg.mass + se.mass, ymin = avg.mass - se.mass),
                width = 0.3, lty = "solid") + # remove if including ctrl
  labs(y = "pupal mass (g)", 
       caption = "mean±se") +
  facet_grid(sex~pop) +
    scale_color_brewer(palette = "Dark2") +
    theme_bw()
}

dfs_dev_ss$ad_dev_bysex %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev_bysex %>%
  filter(trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev_bysex %>%
  filter(trt != 260, sex == "m") %>%
  .plotfn() +
  scale_x_discrete(labels = c("19", "26", "33")) +
  labs(x = "minimum T (°C)")
```

```{r}
# sexes parsed
# by sex (meh)
.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
    ggplot(aes(y = avg.mass, x = trt,
             col = year,
             group = interaction(year, pop), 
             shape = pop, lty = pop
             )) +
  geom_point(size = 2) + geom_line() +
  geom_errorbar(aes(ymax = avg.mass + se.mass, ymin = avg.mass - se.mass),
                width = 0.3, lty = "solid") + # remove if including ctrl
  # geom_text(aes(label = n),
  #           vjust = -0.5, hjust = -0.5, size = 3.5,
  #           position = position_jitter(width = 0.2, height = 0.3, seed = 1),
  #           show.legend = FALSE) + # too busy
  labs(y = "pupal mass (g)", 
       caption = "mean±se") +
  facet_grid(~sex) +
    scale_color_brewer(palette = "Dark2") +
    scale_shape_manual(values = c(1, 16)) +
  scale_linetype_manual(values = c("dashed", "solid")) +
  theme_bw()
}

dfs_dev_ss$ad_dev_bysex %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev_bysex %>%
  filter(trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))
```

```{r}
# sexes parsed
# by pop (no)
.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
    ggplot(aes(y = avg.mass, x = trt,
             col = year,
             group = interaction(year, sex), 
             shape = sex, lty = sex
             )) +
  geom_point(size = 2) + geom_line() +
  geom_errorbar(aes(ymax = avg.mass + se.mass, ymin = avg.mass - se.mass),
                width = 0.3, lty = "solid") +
  labs(y = "pupal mass (g)", 
       caption = "mean±se") +
  facet_grid(~pop) +
    scale_color_brewer(palette = "Dark2") +
    scale_shape_manual(values = c(1, 16)) +
  scale_linetype_manual(values = c("dashed", "solid")) +
  theme_bw()
}

dfs_dev_ss$ad_dev_bysex %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev_bysex %>%
  filter(trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))
```

## pup time

```{r days to pup}
.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
    ggplot(aes(y = avg.tt, x = trt,
               col = year,
               group = year)) +
    geom_point(size = 2) + geom_line() +
    geom_errorbar(aes(ymax = avg.tt + se.tt,
                      ymin = avg.tt - se.tt),
                  width = 0.25) +
    # geom_text(aes(label = n),
    #           vjust = -0.75, hjust = -0.5, size = 3.5,
    #           #position = position_jitter(width = 0.2, height = 0.3, seed = 1),
    #           show.legend = FALSE) +
    facet_grid(~pop) +
    scale_color_brewer(palette = "Dark2") +
    theme_bw() +
    labs(y = "mean±se time to pupation (days)",
         x = "temperature trt",
         title = "time to pupation")
}

dfs_dev_ss$ad_dev %>%
  filter(trt != 260) %>%  
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))
# LOL the 260 lab every yr ...  i think its bc they take so long from 5 to wander
```

```{r pup rate}
.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
    ggplot(aes(y = avg.devrate, x = trt,
               col = year,
               group = year)) +
    geom_point(size = 2) + geom_line() +
    geom_errorbar(aes(ymax = avg.devrate + se.devrate,
                      ymin = avg.devrate - se.devrate),
                  width = 0.25) +
    # geom_text(aes(label = n),
    #           vjust = -0.75, hjust = -0.5, size = 3.5,
    #           #position = position_jitter(width = 0.2, height = 0.3, seed = 1),
    #           show.legend = FALSE) +
    facet_grid(~pop) +
    scale_color_brewer(palette = "Dark2") +
    theme_bw() +
    labs(y = "development rate (1/days)",
         x = "temperature trt",
         title = "time to pupation")
}

dfs_dev_ss$ad_dev %>%
  filter(trt != 260) %>%  
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))
```


## dev trajectories 

```{r}
# dev by year
.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>% 
    filter(instar %in% c("3rd", "4th", "5th", "wander")) %>% #View()
    ggplot(aes(y = avg.logmass,
               x = avg.tt,
               col = year)) +
    geom_point() +
    geom_line() +
    # hard to see with these lol bc theyre pretty close
    # geom_errorbar(aes(ymax = avg.logmass + se.logmass,
    #                   ymin = avg.logmass - se.logmass,
    #                   width = CalcErrWd(avg.tt))) +
    # geom_errorbarh(aes(xmax = avg.tt + se.tt,
    #                    xmin = avg.tt - se.tt,
    #                    height = CalcErrHt(avg.logmass))) +
    facet_grid(pop ~ trt) +
    #scale_color_brewer(palette = "Greens") +
    scale_color_brewer(palette = "Dark2") +
    theme_bw() +
    labs(caption = "mean ± se",
         y = "log(mass mg)", x = "dev time (days)",
         col = "year")
}

dfs_dev_ss$dev_outcomes_all %>%
  .plotfn() +
  labs(title = "development trajectories (with pmd)")

dfs_dev_ss$dev_outcomes_allgrpd %>%
  filter(is.pup != 0) %>%
  .plotfn() +
  labs(title = "development trajectories (pup'd only)", # this actually includes pups + culled lol
       )
```

```{r}
# dev by year; parse out pmds more
.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>% 
    mutate(is.pup = as.factor(is.pup)) %>%
    filter(instar %in% c("3rd", "4th", "5th", "wander")) %>% #View()
    ggplot(aes(y = avg.logmass,
               x = avg.tt,
               col = year, lty = is.pup, 
               group = interaction(year, is.pup, trt, pop))) +
    geom_point() +
    geom_line() +
    facet_grid(pop ~ trt) +
    scale_color_brewer(palette = "Dark2") +
    theme_bw() +
    labs(title = "development trajectories",
         caption = "mean ± se",
         y = "log(mass mg)", x = "dev time (days)",
         col = "year", lty = "fate"
    ) +
    scale_linetype_discrete(labels = c("pupated", "died"))
}

# surv + culled combined
dfs_dev_ss$dev_outcomes_allgrpd %>%
  .plotfn()


# culled omitted
dfs_dev_ss$dev_outcomes_allgrpd2 %>%
  filter(is.pup != 2) %>%
  .plotfn()
```

```{r}
# dev by trt
.plotfn <- function(x){
  x %>%
  FilterOutLabTB() %>% 
  filter(instar %in% c("3rd", "4th", "5th", "wander")) %>% 
  ggplot(aes(y = avg.logmass,
             x = avg.tt,
             col = trt)) +
  geom_point() +
  geom_line() +
  # hard to see with these lol bc theyre pretty close
  # geom_errorbar(aes(ymax = avg.logmass + se.logmass,
  #                   ymin = avg.logmass - se.logmass,
  #                   width = CalcErrWd(avg.tt))) +
  # geom_errorbarh(aes(xmax = avg.tt + se.tt,
  #                    xmin = avg.tt - se.tt,
  #                    height = CalcErrHt(avg.logmass))) +
  facet_grid(pop ~ year) +
  #scale_color_brewer(palette = "Greens") +
  #scale_color_manual(values = hcl.colors(6, "Viridis", rev = TRUE)) +
    scale_color_manual(values = c("#00A3B6", "#4B1D91", "#A71B4B", "#F9C25C"),
                       labels = c("26-26", "40-19", "40-26", "40-33")) +
    labs(caption = "mean ± se",
         y = "log(mass mg)", x = "dev time (days)",
         col = "treatment") +
    theme_bw()
}

dfs_dev_ss$dev_outcomes_allgrpd %>%
  filter(is.pup != 0) %>%
  .plotfn() +
  labs(title = "development trajectories (pups only)")

dfs_dev_ss$dev_outcomes_all %>%
  .plotfn() +
  labs(title = "development trajectories (all)")
```
```{r}
# dev traj by trt + surv to pupation
.plotfn <- function(x){
  x %>%
  FilterOutLabTB() %>% 
    mutate(is.pup = case_when(is.pup == 0 ~ "died",
                                is.pup == 1 ~ "pupated")) %>%
    mutate(is.pup = factor(is.pup, levels = c("pupated", "died"))) %>%
  filter(instar %in% c("3rd", "4th", "5th", "wander")) %>% 
  ggplot(aes(y = avg.logmass,
             x = avg.tt,
             col = trt,
             group = interaction(year, pop, is.pup, trt))) +
  geom_point() +
  geom_line() +
  # hard to see with these lol bc theyre pretty close
  # geom_errorbar(aes(ymax = avg.logmass + se.logmass,
  #                   ymin = avg.logmass - se.logmass,
  #                   width = CalcErrWd(avg.tt))) +
  # geom_errorbarh(aes(xmax = avg.tt + se.tt,
  #                    xmin = avg.tt - se.tt,
  #                    height = CalcErrHt(avg.logmass))) +
  facet_grid(is.pup ~ year) +
  #scale_color_brewer(palette = "Greens") +
  #scale_color_manual(values = hcl.colors(6, "Viridis", rev = TRUE)) +
    scale_color_manual(values = c("#00A3B6", "#4B1D91", "#A71B4B", "#F9C25C"),
                       labels = c("26-26", "40-19", "40-26", "40-33")) +
    labs(caption = "mean ± se",
         y = "log(mass mg)", x = "dev time (days)",
         col = "treatment") +
    theme_bw()
}

dfs_dev_ss$dev_outcomes_allgrpd2 %>%
  filter(is.pup != 2, pop == "field") %>% 
  .plotfn() +
  labs(title = "development trajectories (field)")

dfs_dev_ss$dev_outcomes_allgrpd2 %>%
  filter(is.pup != 2, pop == "lab") %>%
  .plotfn() +
  labs(title = "development trajectories (lab)")
```


```{r}
# wtf goin on w the lab controls
dfs_dev_ss$dev_outcomes_all %>%
  FilterOutLabTB() %>% 
  filter(instar %in% c("3rd", "4th", "5th", "wander", "pupa"),
         trt == 260) %>% #View()
  ggplot(aes(y = avg.logmass,
             x = avg.tt,
             col = year, lty = pop, shape = pop,
             group = interaction(year, pop))) +
  geom_errorbarh(aes(xmax = avg.tt + se.tt,
                     xmin = avg.tt - se.tt,
                     height = 0.3), lty = "solid") +
  geom_point() +
  geom_line() +
  facet_grid(#pop 
             ~ trt) +
  #scale_color_brewer(palette = "Greens") +
  scale_color_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(16, 1)) +
  labs(caption = "what's up w the controls") +
  theme_bw()
```


## supernumerary

```{r}
dfs_dev_ss$sup_outcomes %>% 
  FilterOutLabTB() %>%
  filter(status == "surv") %>%
  ggplot(aes(y = p,
             x = interaction(trt),
             fill = sup)) +
  geom_col() +
  geom_text(data = . %>% distinct(interaction(year, trt, pop), .keep_all = TRUE), 
            aes(label = N), y = 0.1) +
  facet_grid(pop~year) +
  labs(title = "# instars before pupation",
       y = "proportion survived", x = "trt",
       fill = "extra instars",
       caption = "N = total entered") +
  guides(x = guide_axis(angle = 45)) +
  scale_fill_brewer(palette = "Blues", direction = -1,
                    labels = c("0", "1", "2", "3", "died")) +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33")) +
  #scale_fill_discrete(labels = c("0", "1", "2", "3", "died")) +
  theme_bw()
```
