---
title: "wrangle-tdt"
date: "2025-06-16"
---

# 0. preamble

wrangling 2025 tdt data

final code is purled to a `.R` script, manually rerun `purl()` as needed to update the wrangling script for analyses

```{r wrangle setup and purling, eval=FALSE, include=FALSE, purl=FALSE}
# run manually when new wrangle script is needed
knitr::purl("wrangle-tdt.Rmd", "wrangle-tdt_p.R")

# archive
here::i_am("2025/wrangle-tdt.Rmd")
library(here)
source(here::here("set-paths.R"))
knitr::purl("wrangle-tdt.Rmd", paste0(here(bin_paths$y25$root), 
                                      "/wrangle-archive/", format(Sys.time(), "%y%m%d"), "_wrangle-tdt_p.R"))
```


# 1. loading

```{r about, echo=TRUE, eval = TRUE}
# wrangle-tdt.R

# knitted wrangling code for 2025 tdt data
# source() this in corresponding analysis scripts.
```

```{r load utils}
#here::i_am("2025/analysis-tdt.Rmd")
library(here)

source(here::here("set-paths.R"))

library(tidyverse)
# library(conflicted)
# conflicts_prefer(dplyr::filter)
```

```{r load data}
data <- read.csv(here(bin_paths$y25$data, "clean-working.csv"), header = TRUE)
```

# 2. prep for km

## - calc exit times; recode events

```{r} 
# recode exit times


# find max dh.exit for expt bugs, use this # as the basis for the others (add +1 to it?)
max <- data %>%
  filter(trt > 100) %>%
  summarise(max(dh.exit)) %>%
  pull()


# create new list
km <- list()

# recode times for ctrls... (tho they will be dropped later lol)
  # things that die before recovery/returning should be NA!!!!!
km <- list_assign(km, data = data %>%
                    mutate(dh.exit = case_when(is.na(dh.exit) ~ max + 2,
                                               TRUE ~ dh.exit),
                           
                           ## ctrls should not have a recover/return time lol
                           # dh.recover = case_when(trt < 100 & is.na(dh.recover) ~ dh.enter,
                           #                        TRUE ~ dh.recover),
                           # dh.return = case_when(trt < 100 & is.na(dh.return) ~ dh.enter,
                           #                       TRUE ~ dh.return),
                           
                           ## standardise exit times by trt enter date (enter date = d0)
                           # doesnt super make sense to start at hatch date..
                           tt.enter = dh.enter - dh.enter,
                           tt.recover = dh.recover - dh.enter,
                           tt.return = dh.return - dh.enter,
                           tt.exit = dh.exit - dh.enter,
                           
                    )
                  )


  
```

```{r}
# add some binaries; recalc other times

km <- list_assign(km, data = km$data %>% mutate(
                                                # exit times, except this doesnt make sense lol... recalc w tt.times?
                                                # exit.fromhatch = dh.exit - dh.hatch,
                                                # exit.fromenter = dh.exit - dh.enter,
                                                # exit.fromrecover = dh.exit - dh.recover,
                                                # exit.fromreturn = dh.exit - dh.return,
                                                
                                                exit.fromenter = tt.exit - tt.enter,
                                                exit.fromrecover = tt.exit - tt.recover,
                                                exit.fromreturn = tt.exit - tt.return,
  
                                                is.40C = case_when(trt.enter == 40 ~ "Y",
                                                                   TRUE ~ "N"),
                                                is.ctrl = case_when(trt < 100 ~ "Y",
                                                                    TRUE ~ "N"),
                                                trt.recover = case_when(is.na(trt.recover) ~ trt.enter,
                                                                        TRUE ~ trt.recover),
                                                trt.lab = formatC(trt, width = 3, flag = "0")
                                                )
                  )


# redo km statuses
  # 1 = death, 0 = censored
km <- list_assign(km, data = km$data %>% mutate(km.status = case_when(dh.exit > max ~ 0,
                                                                      TRUE ~ 1)))

# extract subsets
km <- list_assign(km, subsets = list(ctrls = filter(km$data, trt.enter == trt.recover),
                                     expts = filter(km$data, trt.enter != trt.recover),
                                     only40 = filter(km$data, trt.enter == 40),
                                     rec24 = filter(km$data, trt == 40 | trt.duration == 24),
                                     rec48 = filter(km$data, trt == 40 | trt.duration == 48)))


```

## - (archived)

```{r df prep for in progress data, eval=FALSE, include=FALSE, purl=FALSE}
## originally for doing analysis while bugs were in progress...
## TODO figure out what to do w this... need to wrangle the data a bit tho (see below section)

# for now, censor if they get to 4th
data <- data %>%
  mutate(fate = case_when(!is.na(jdate.4th) ~ 1,
                          TRUE ~ as.numeric(fate)))

# for bugs in progress, arbitrarily add today as a censor...?
data <- data %>%
  mutate(now = as.numeric(as.Date(today(), format = "%j")),
         dv.exit = case_when(is.na(jdate.exit) ~ now + 25580,
                                TRUE ~ dv.exit),
         fate = case_when(dv.exit == now ~ 1,
                          TRUE ~ fate))

# change duration to when entered (aka subtr out the buffer)
```

```{r df prep for km fits, eval=FALSE, include=FALSE, purl=FALSE}

### TODO wonky bc it uses the old julian dates, but holding onto this cuz just in case but otherwise rewritten above

# also JK for km curves, 1 = death and 0 = censored
# and adding other exit info...
km.data <- data %>% 
  #drop_na(fate) %>%
  mutate(km.status = case_when(!is.na(jdate.4th) ~ 0,
                          !is.na(jdate.exit) ~ 1),
         # not sure how to incorporate the dv stuff for 4ths...
         km.exit = case_when(!is.na(jdate.4th) ~ jdate.4th + 25580,
                             !is.na(dv.exit) ~ dv.exit),
         instar.exit = case_when(!is.na(jdate.4th) ~ 4,
                                 TRUE ~ as.numeric(instar.exit)),
         is.40 = case_when(trt.enter == 40 ~ "Y",
                          TRUE ~ "N"),
         is.ctrl = case_when(trt < 100 ~ "Y",
                             TRUE ~ "N"),
         trt.recover = case_when(is.ctrl == "Y" ~ trt.enter,
                                 TRUE ~ trt.recover))
```


```{r cleanup}
rm(max)

```


