---
title: "2024 dev data cleaning"
date: "2024-07-15"
---

# roadmap

1. load data & packages
2. cleaning: filtering, column formatting + rearrangement
3. save output

(borrowing a lot of code from `2023/cleaning_ntw`)

# 1. load data & packages
```{r message = FALSE}
library(conflicted)
library(dplyr)
library(tidyr)
library(purrr)
library(googlesheets4)
```

# googlesheets import & pre-formatting

- TODO 2024-07-15: check if columns need to be standardised (i.e. needs macros?)
  - 7/15: yes LOL the dates are broken bc of the year

```{r}
data <- read_sheet("https://docs.google.com/spreadsheets/d/1TOUsH7zNT6jF7SltYsD_8pK5tI7yR-Gqx-kDrodmJ00/edit?gid=1256964024", sheet = "july pilot", col_types = "c")
```

```{r}
fix.columns <- function(data) {
  cleaned_data <- data %>%
    mutate(across(starts_with("date."),  as.Date, format = "%m/%d"),
           #across(starts_with("date."), format(., "%m/%d/%Y"))) 
           )%>%
    mutate(mutate(across(starts_with("mass."), as.numeric))
    )
  
  return(cleaned_data)
}

data <- fix.columns(data)
```

