---
title: "01-cleaning/tents"
date: "2025-01-13"
---

stealing from `2023/cleaning_tents.Rmd` again!!

(cleans 2024 tents data only)

# roadmap

1.  load data & packages
2.  cleaning: prefiltering, fix columns, add columns, value fixing
3.  save output

LAST RUN: 2026-03-16 (fixing 2099)

# load data & packages

```{r message = FALSE}
library(tidyverse)
library(googlesheets4)

here::i_am("_ntw/scripts/import/2024-tents.Rmd")
library(here)
```

## data import from gsheets

```{r}
# before importing,
  # run cleaning macros,
  # check column/row alignment + proper sorting

dfs_raw <- list(
  tents = read_sheet("https://docs.google.com/spreadsheets/d/1TOUsH7zNT6jF7SltYsD_8pK5tI7yR-Gqx-kDrodmJ00/edit?gid=1854350692", sheet = "tents", range = "A:N", col_types = "c", na = c("", "n/a")),
  
  tentstats = read_sheet("https://docs.google.com/spreadsheets/d/1TOUsH7zNT6jF7SltYsD_8pK5tI7yR-Gqx-kDrodmJ00/edit?gid=641809244", sheet = "tent stats", range = "A:Q", col_types = "c", na = c("", "#REF!", "#N/A"))
)
```

# cleaning

## filtering rows/cols, renaming
```{r}
dfs_filtered <- list(
  tents = dfs_raw$tents %>%
    filter(sex == "f",
           !is.na(uid2)) %>%
    select(-c("mass.eclose", "combo",
              "uid", "id.cage", "id.tent")) %>%
    rename(cage = uid2,
           date.died = date.surv),
  
  events = dfs_raw$tentstats %>%
    filter(sex == "f",
           !is.na(uid2) # corresponds to `processed %in% c(x, y)`
           ) %>%
    select(-c("uid", "id.tent", "id.cage",
              "combo", "processed?")) %>%
    rename(cage = uid2,
           eggs.collected = "eggs collected",
           f.added = added,
           f.curr = alive,
           f.removed = removed,
           f.died = died,
           f.active = "females laying" # pre-calculated in gsheet
           )
)
```

## mutate cols; value fixes; formatting

```{r}
dfs_cleaned <- list(
  tents = dfs_filtered[["tents"]] %>%
    mutate(if.def = case_when(grepl("bad|wing.", notes) ~ "x"),
           date.tent = case_when(is.na(date.tent) ~ date.eclose,
                                 TRUE ~ date.tent)),
  
  events = dfs_filtered[["events"]]
  
  # events = dfs_filtered[["events"]] %>%
  #   # add missing leading 0s to day portion of date
  #   mutate(date = case_when(grepl("^(\\d{2}/\\d{1}/)", date) ~ 
  #                                   gsub("^(\\d{2}/)(.*)$", "\\10\\2", date),
  #                           TRUE ~ date
  #                           ))
  #   
)

dfs_cleaned <- dfs_cleaned %>%
  lapply(., \(x){
    x %>%
      mutate(across(starts_with("date"), as.Date, format = "%m/%d/%y"),
             across(starts_with(c("date", "f.", "eggs.", "trt", "id")), as.numeric)
      ) %>%
      rename_with(~ paste0("j", .x), starts_with("date"))
  })
```

# export

```{r}
# raw
today <- format(Sys.time(), "%y%m%d-%H%M")

write.csv(dfs_raw$tents, 
          file = paste0(here("_ntw/data/raw/2024/"), "tent-matings_", today, ".csv"),
          row.names = FALSE)
write.csv(dfs_raw$tentstats, 
          file = paste0(here("_ntw/data/raw/2024/"), "tent-events_", today, ".csv"),
          row.names = FALSE)

# cleaned
export <- dfs_cleaned %>%
  lapply(., \(x){
    x %>% select(-"notes")
  })

write.csv(export$tents, file = paste0(here("_ntw/data/clean/2024/"),
                                      "tent-matings.csv"), row.names = FALSE)
write.csv(export$events, file = paste0(here("_ntw/data/clean/2024/"),
                                       "tent-events.csv"), row.names = FALSE)
```

```{r}
# clean up
rm(dfs_raw, dfs_filtered, dfs_cleaned, 
   today, export)
```