---
title: "03-stats/compare-tents"
date: "2025-03-20"
---

# setup

```{r}
here::i_am("2024/03-stats/compare-tents.Rmd")
library(here)

library(tidyverse)
library(lme4) # for lmer.. for tent stuff
#library(MuMIn) # for survival nested model comparisons

source(here::here("set-paths.R"))
source(here::here(bin_paths$y24$wrangle, "compare-tents_p.R"))
```

```{r setting up blank lists for outputs}
dfs <- list()
mods <- list()
```

## - df prep

```{r general df modifications}
# add binaries for modeling
dall <- dall %>%
  mutate(is.hsF = case_when(trt.sex %in% c("f", "both") ~ 1,
                            TRUE ~ 0),
         is.hsM = case_when(trt.sex %in% c("m", "both") ~ 1,
                            TRUE ~ 0))
```

```{r egg stats}
dfs <- list_assign(dfs, 
                   df23 = dall %>%
                     filter(year == 2023) %>%
                     group_by(id) %>%
                     mutate(n.coll.overall = sum(n.coll, na.rm = TRUE),
                            n.f.overall = sum(n.new.f, na.rm=TRUE),
                            n.collperovi.overall = n.coll.overall/n.f.overall,
                            n.hatched.overall = sum(n.hatch, na.rm =TRUE),
                            p.hatched = n.hatched.overall/n.coll.overall,
                            jdate.rel = jdate - first(jdate)
                     ) %>%
                     group_by(jdate.rel, .add = TRUE) %>%
                     mutate(n.coll.daily = sum(n.coll, na.rm = TRUE),
                            #n.hatch.daily = sum(n.hatch, na.rm = TRUE)
                            n.collperovi.daily = n.coll.daily/n.ovi)
)

# try as a summary instead
dfs <- list_assign(dfs, 
                   df23.ss = dall %>%
                     filter(year == 2023 & pop == "lab") %>%
                     group_by(id, is.hsF, is.hsM, trt.temp,
                              # year, pop, trt.type, trt.sex
                              ) %>%
                     mutate(jdate.rel = jdate-first(jdate)) %>%
                     #group_by(jdate.rel, .add = TRUE) %>%
                     summarise(n.coll.overall = sum(n.coll, na.rm = TRUE),
                               n.f.overall = sum(n.new.f, na.rm=TRUE),
                               n.collperovi.overall = n.coll.overall/n.f.overall,
                               #n.coll.daily = sum(n.coll, na.rm = TRUE),
                               #n.hatch.daily = sum(n.hatch, na.rm = TRUE)
                               #n.collperovi.daily = n.coll.daily/n.ovi
                               ) %>%
                     mutate(id2 = paste(is.hsF, is.hsM, trt.temp, sep = "-"))
                   )

# 2023 ver ref
# summ_hatchall <- data_tstats %>%
#   replace(is.na(.), 0) %>%
#   group_by(id.tent) %>%
#   mutate(jdate.rel = jdate - first(jdate)) %>%
#   group_by(jdate.rel) %>%
#   mutate(n.tothatch.pertent = sum(n.tothatch),
#          n.coll.pertent = sum(n.coll)) %>%
#   ungroup() %>%
#   group_by(trt.f, trt.m, pop) %>%
#   mutate(n.tothatch.overall = sum(n.tothatch),
#          n.coll.overall = sum(n.coll),
#          #n.duration.overall = jdate-first(jdate),
#          # below borrowed from LB hatching stuff
#          n.collected = sum(n.coll),
#          n.hatched = sum(n.tothatch),
#          n.females = sum(n.new.f),
#          prop.hatch = n.hatched/n.collected,
#          rate.collf = n.collected/n.females,
#          lt.hprop = log(prop.hatch + 1)) 
#   
# summ_hatchmod <- summ_hatchall %>%
#   filter(n.tothatch.overall > 0)

dfs <- list_assign(dfs, df23_nona = na.omit(dfs$df23))
  
```

# egg laying

## - 2025-03-20

```{r warning=FALSE}
# on unsummed data
mods <- list_assign(mods, 
                    y23.overall = glm(n.collperovi.overall ~ trt.temp*is.hsF*is.hsM, 
                                       data = dfs$df23, family = "poisson")) 
                    # is doing this on the "overall" right? or do per day? (random effs?)

anova(mods$y23.overall, test = "Chisq")

```

```{md}
Model: poisson, link: log

Response: n.collperovi.overall

Terms added sequentially (first to last)


                       Df Deviance Resid. Df Resid. Dev  Pr(>Chi)    
NULL                                     430      55557              
trt.temp                1    984.6       429      54572 < 2.2e-16 ***
is.hsF                  1  10477.0       428      44095 < 2.2e-16 ***
is.hsM                  1    191.2       427      43904 < 2.2e-16 ***
trt.temp:is.hsF         1    183.2       426      43721 < 2.2e-16 ***
trt.temp:is.hsM         1   2348.8       425      41372 < 2.2e-16 ***
is.hsF:is.hsM           0      0.0       425      41372              
trt.temp:is.hsF:is.hsM  0      0.0       425      41372 
```

## - 2025-03-26

see comments but tldr trying `id` (of tent) as a rand eff doesnt work bc there's some colinearity

```{r warning=FALSE}
# summed y23
mods <- list_assign(mods, 
                    y23ss.overall = glm(n.collperovi.overall ~ trt.temp*is.hsF*is.hsM, 
                                       data = dfs$df23.ss, family = "poisson")) 
                    # is doing this on the "overall" right? or do per day? (random effs?)

anova(mods$y23ss.overall, test = "Chisq")

# trying random effects? (tent id, # of females?)
mods <- list_assign(mods, 
                    y23ss.randid = glmer(n.collperovi.overall ~ trt.temp*is.hsF*is.hsM + (1|id), 
                                       data = dfs$df23.ss, family = poisson)) 

anova(mods$y23ss.randid, test = "Chisq") 
# wonky bc some trts only have 1 tent (npar = 1). need to filter -- JK, see below
# have some "singular" fits bc in some combos of trt*ishs, colA + colB = colC

dfs <- list_assign(dfs, df23.ssdups = dfs$df23.ss %>%
                     #mutate(id2 = paste(is.hsF, is.hsM, trt.temp, sep = "-")) %>%
                     group_by(id2) %>%
                     filter(n() > 1) %>% # get the dups
                     ungroup()
                   )

mods <- list_assign(mods,
                    y23ss.randid2 = glmer(n.collperovi.overall ~ trt.temp*is.hsF*is.hsM + (1|id),
                                       data = dfs$df23.ssdups), family = poisson)

#anova(mods$y23ss.randid2, test = "Chisq")

# this does not work as planned bc effectively, every id only has 1 observation (i.e. combo of trt temp/is.hs), so nothing is "random"
# sorta would work if using (1|id2) instead but still issues w singularity (see)

```

```{md}
# y23ss.overall
Model: poisson, link: log

Response: n.collperovi.overall

Terms added sequentially (first to last)


                       Df Deviance Resid. Df Resid. Dev  Pr(>Chi)    
NULL                                      25     3183.9              
trt.temp                1   129.18        24     3054.7 < 2.2e-16 ***
is.hsF                  1   400.98        23     2653.7 < 2.2e-16 ***
is.hsM                  1     6.02        22     2647.7   0.01414 *  
trt.temp:is.hsF         1     0.21        21     2647.5   0.64565    
trt.temp:is.hsM         1    56.50        20     2591.0 5.619e-14 ***
is.hsF:is.hsM           0     0.00        20     2591.0              
trt.temp:is.hsF:is.hsM  0     0.00        20     2591.0      

# so additive terms matter and HS trt of the male for egg production (why the male LOL..)
# maybe things to look into: eff of # of females? daily rate? (depends on what the "unit" of the response variable is...)
```

# hatching

## - 2025-04-27
```{r}
# logit transform response
dfs <- list_assign(dfs, 
                   hatchstats = dfs$df23 %>%
                     mutate(z.logit = log(p.hatched/(1-p.hatched)), # dont use lol
                            z.mod = p.hatched + 0.005,
                            z.logit2 = log((z.mod/(1-z.mod))))
)
#View(dfs[["hatchstats"]])
```

```{r}
# try as a LM...
anova(lm(z.logit2 ~ as.factor(trt.temp)*is.hsF*is.hsM, 
   data = dfs$hatchstats, na.action = na.omit))


# try as a binomial...
# (not working... lol)
anova(glm(c(n.hatched.overall, n.coll.overall) ~ as.factor(trt.temp)*is.hsF*is.hsM, 
   data = dfs$hatchstats, family = "binomial"))

anova(glm(c(n.hatched.overall, n.coll.overall-n.hatched.overall) ~ factor(trt.temp)*is.hsF*is.hsM, 
   data = dfs$hatchstats, family = "binomial", na.action = na.omit))
```


