---
title: "ntw 2025 data viz"
date: "2025-12-01"
---

# # preamble & loading

data viz for ntw 2025

```{r set pathfinding}
here::i_am("2025/ntw/analysis-viz.Rmd")
library(here)
```

```{r load libraries}
library(tidyverse)
library(patchwork) # for plot_layout
# library(survival) # for fitting surv
# library(survminer) # for plotting surv
```

```{r load data and helpers, message = FALSE, warning=FALSE}
source(here::here("set-paths.R"))
source(here(bin_paths$y25$ntw, "/utils/general.R"))
source(here(bin_paths$y25$ntw, "/utils/analysis-viz.R"))
source(here(bin_paths$y25$ntw, "/R/wrangle-data.R"))
rm(dfs_pertent_ss)
```

```{r}
# convert things into factors for ease of graphing
dfs_dev_ss <- dfs_dev_ss %>%
    lapply(., \(x){
    x %>%
      ungroup() %>%
      mutate(across(c("year", "trt"), as.factor))
  })

dfs_tents_ss <- dfs_tents_ss %>%
    lapply(., \(x){
    x %>%
      ungroup() %>%
      mutate(across(c("year", "mate.trt", starts_with("trt")), as.factor),
             mate.type = factor(mate.type, 
                                levels = c("within", "between")))
  })
  
```

# # overall dev

## survival to pup
```{r}
.plotfn <- function(x){
  x %>%
  FilterOutLabTB() %>%
  ggplot(aes(y = prop.pup,
             x = trt,
             col = year, lty = year,
             group = year
             )) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymax = prop.pup + se.pup,
                    ymin = prop.pup - se.pup),
                width = 0.25, lty = "solid", show.legend = FALSE) +
  # geom_text(aes(label = n),
  #           hjust = -0.2, vjust = -.2,
  #           show.legend = FALSE) +
  facet_wrap(~pop) +
  labs(y = "survived to pupation",
       x = "treatment",
       col = "year", lty = "year") +
  scale_color_brewer(palette = "Dark2") +
  theme_bw()
}

dfs_dev_ss$surv_outcomes %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_dev_ss$surv_outcomes %>%
  filter(trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("19", "26", "33")) +
  labs(x = "minimum T (°C)")

```

## pup mass

```{r}
# sexes combined
.plotfn <- function(x){
  x %>%
      FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
  ggplot(aes(y = avg.mass, x = trt,
             #lty = year, 
             col = year,
             group = year,
             ))+
  geom_point() + geom_line() +
  geom_errorbar(aes(ymax = avg.mass + se.mass, 
                    ymin = avg.mass - se.mass),
                width = 0.3, lty = "solid") +
  # geom_text(aes(label = n),
  #           vjust = -0.2, hjust = -0.3,
  #           show.legend = FALSE) +
  facet_grid(~pop) +
  labs(y = "pupal mass (g)",
       caption = "mean±se; combined sexes") +
  scale_color_brewer(palette = "Dark2") +
  theme_bw()
}


dfs_dev_ss$ad_dev%>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev%>%
  filter(trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))
```

```{r}
# sexes parsed
# 2x2 pop + sex (better)

.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
    ggplot(aes(y = avg.mass, x = trt,
             col = year,
             group = interaction(year)
             )) +
  geom_point() + geom_line() +
    # geom_text(aes(label = n),
  #           vjust = -0.5, hjust = -0.5, size = 3.5,
  #           position = position_jitter(width = 0.2, height = 0.3, seed = 1),
  #           show.legend = FALSE) + # too busy
    geom_errorbar(aes(ymax = avg.mass + se.mass, ymin = avg.mass - se.mass),
                width = 0.3, lty = "solid") + # remove if including ctrl
  labs(y = "pupal mass (g)", 
       caption = "mean±se") +
  facet_grid(sex~pop) +
    scale_color_brewer(palette = "Dark2") +
    theme_bw()
}

dfs_dev_ss$ad_dev_bysex %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev_bysex %>%
  filter(trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev_bysex %>%
  filter(trt != 260, sex == "m") %>%
  .plotfn() +
  scale_x_discrete(labels = c("19", "26", "33")) +
  labs(x = "minimum T (°C)")
```

```{r}
# sexes parsed
# by sex (meh)
.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
    ggplot(aes(y = avg.mass, x = trt,
             col = year,
             group = interaction(year, pop), 
             shape = pop, lty = pop
             )) +
  geom_point(size = 2) + geom_line() +
  geom_errorbar(aes(ymax = avg.mass + se.mass, ymin = avg.mass - se.mass),
                width = 0.3, lty = "solid") + # remove if including ctrl
  # geom_text(aes(label = n),
  #           vjust = -0.5, hjust = -0.5, size = 3.5,
  #           position = position_jitter(width = 0.2, height = 0.3, seed = 1),
  #           show.legend = FALSE) + # too busy
  labs(y = "pupal mass (g)", 
       caption = "mean±se") +
  facet_grid(~sex) +
    scale_color_brewer(palette = "Dark2") +
    scale_shape_manual(values = c(1, 16)) +
  scale_linetype_manual(values = c("dashed", "solid")) +
  theme_bw()
}

dfs_dev_ss$ad_dev_bysex %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev_bysex %>%
  filter(trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))
```

```{r}
# sexes parsed
# by pop (no)
.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
    ggplot(aes(y = avg.mass, x = trt,
             col = year,
             group = interaction(year, sex), 
             shape = sex, lty = sex
             )) +
  geom_point(size = 2) + geom_line() +
  geom_errorbar(aes(ymax = avg.mass + se.mass, ymin = avg.mass - se.mass),
                width = 0.3, lty = "solid") +
  labs(y = "pupal mass (g)", 
       caption = "mean±se") +
  facet_grid(~pop) +
    scale_color_brewer(palette = "Dark2") +
    scale_shape_manual(values = c(1, 16)) +
  scale_linetype_manual(values = c("dashed", "solid")) +
  theme_bw()
}

dfs_dev_ss$ad_dev_bysex %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev_bysex %>%
  filter(trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))
```
## pup time

```{r}
.plotfn <- function(x){
  x %>%
    FilterOutLabTB() %>%
    filter(instar == "pupa") %>%
     ggplot(aes(y = avg.tt, x = trt,
             col = year,
             group = year)) +
  geom_point(size = 2) + geom_line() +
  geom_errorbar(aes(ymax = avg.tt + se.tt,
                    ymin = avg.tt - se.tt),
                width = 0.25) +
  # geom_text(aes(label = n),
  #           vjust = -0.75, hjust = -0.5, size = 3.5,
  #           #position = position_jitter(width = 0.2, height = 0.3, seed = 1),
  #           show.legend = FALSE) +
  facet_grid(~pop) +
  scale_color_brewer(palette = "Dark2") +
  theme_bw()
}

dfs_dev_ss$ad_dev %>%
  filter(trt != 260) %>%  
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))

dfs_dev_ss$ad_dev %>%
  .plotfn() +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))
# LOL the 260 lab every yr ...  i think its bc they take so long from 5 to wander
```


## dev trajectories 

```{r}
# dev by year
.plotfn <- function(x){
  x %>%
  FilterOutLabTB() %>% 
  filter(instar %in% c("3rd", "4th", "5th", "wander")) %>% #View()
  ggplot(aes(y = avg.logmass,
             x = avg.tt,
             col = year)) +
  geom_point() +
  geom_line() +
  # hard to see with these lol bc theyre pretty close
  # geom_errorbar(aes(ymax = avg.logmass + se.logmass,
  #                   ymin = avg.logmass - se.logmass,
  #                   width = CalcErrWd(avg.tt))) +
  # geom_errorbarh(aes(xmax = avg.tt + se.tt,
  #                    xmin = avg.tt - se.tt,
  #                    height = CalcErrHt(avg.logmass))) +
  facet_grid(pop ~ trt) +
  #scale_color_brewer(palette = "Greens") +
  scale_color_brewer(palette = "Dark2") +
  theme_bw()
}

dfs_dev_ss$dev_outcomes_nopmd %>%
  .plotfn() +
  labs(title = "development trajectories (pup'd only)",
       caption = "mean ± se",
       y = "log(mass mg)", x = "dev time (days)",
       col = "year",
       )


dfs_dev_ss$dev_outcomes_wpmd %>%
  .plotfn() +
  labs(title = "development trajectories (with pmd)",
       caption = "mean ± se",
       y = "log(mass mg)", x = "dev time (days)",
       col = "year",
       )
```

```{r}
# dev by trt
.plotfn <- function(x){
  x %>%
  FilterOutLabTB() %>% 
  filter(instar %in% c("3rd", "4th", "5th", "wander")) %>% 
  ggplot(aes(y = avg.logmass,
             x = avg.tt,
             col = trt)) +
  geom_point() +
  geom_line() +
  # hard to see with these lol bc theyre pretty close
  # geom_errorbar(aes(ymax = avg.logmass + se.logmass,
  #                   ymin = avg.logmass - se.logmass,
  #                   width = CalcErrWd(avg.tt))) +
  # geom_errorbarh(aes(xmax = avg.tt + se.tt,
  #                    xmin = avg.tt - se.tt,
  #                    height = CalcErrHt(avg.logmass))) +
  facet_grid(pop ~ year) +
  #scale_color_brewer(palette = "Greens") +
  scale_color_manual(values = hcl.colors(6, "Viridis", rev = TRUE))
}

dfs_dev_ss$dev_outcomes_nopmd %>%
  .plotfn() +
  labs(title = "development trajectories (pups only)",
       caption = "mean ± se",
       y = "log(mass mg)", x = "dev time (days)",
       col = "treatment",
  )

dfs_dev_ss$dev_outcomes_wpmd %>%
  .plotfn() +
  labs(title = "development trajectories (all)",
       caption = "mean ± se",
       y = "log(mass mg)", x = "dev time (days)",
       col = "treatment",
       )
```

```{r}
# wtf goin on w the lab controls
dfs_dev_ss$dev_outcomes_wpmd %>%
  FilterOutLabTB() %>% 
  filter(instar %in% c("3rd", "4th", "5th", "wander", "pupa"),
         trt == 260) %>% #View()
  ggplot(aes(y = avg.logmass,
             x = avg.tt,
             col = year, lty = pop, shape = pop,
             group = interaction(year, pop))) +
  geom_errorbarh(aes(xmax = avg.tt + se.tt,
                     xmin = avg.tt - se.tt,
                     height = 0.3), lty = "solid") +
  geom_point() +
  geom_line() +
  facet_grid(#pop 
             ~ trt) +
  #scale_color_brewer(palette = "Greens") +
  scale_color_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(16, 1)) +
  labs(caption = "what's up w the controls") +
  theme_bw()
```


## supernumerary

```{r}
dfs_dev_ss$sup_outcomes %>% 
  FilterOutLabTB() %>%
  filter(status == "surv") %>%
  ggplot(aes(y = p,
             x = interaction(trt),
             fill = sup)) +
  geom_col() +
  geom_text(data = . %>% distinct(interaction(year, trt, pop), .keep_all = TRUE), 
            aes(label = N), y = 0.1) +
  facet_grid(pop~year) +
  labs(title = "# instars before pupation",
       y = "proportion survived", x = "trt",
       fill = "extra instars",
       caption = "N = total entered") +
  guides(x = guide_axis(angle = 45)) +
  scale_fill_brewer(palette = "Blues", direction = -1,
                    labels = c("0", "1", "2", "3", "died")) +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33")) +
  #scale_fill_discrete(labels = c("0", "1", "2", "3", "died")) +
  theme_bw()
```

# # tents

## hatch+laid btwn yrs 

```{r}
# both yrs
dfs_tents_ss$eggs_nocol %>%
  FilterForLabEggs() %>%
  ggplot(aes(y = p.eggs.hatched, x = n.eggs.coll,
             col = mate.trt, shape = mate.hs)) +
  geom_point() +
  geom_errorbar(aes(ymax = p.eggs.hatched + se.eggs.hatched,
                    ymin = p.eggs.hatched - se.eggs.hatched),
                width = 100) +
  # x err bar is too small to notice for 2025
  facet_wrap(mate.type ~ year) +
  #labs(x = "total eggs collected") +
  scale_color_brewer(palette = "Dark2")
```

```{r}
# sep years
.plotfn <- function(x){
  x %>%
    FilterForLabEggs() %>%
    ggplot(aes(y = p.eggs.hatched, x = n.eggs.coll,
               col = mate.trt, shape = mate.hs)) +
    geom_point(size = 2) +
    geom_errorbar(aes(ymax = p.eggs.hatched + se.eggs.hatched,
                      ymin = p.eggs.hatched - se.eggs.hatched),
                  width = CalcErrWd(x = dfs_tents_ss$eggs_nocol$n.eggs.coll, 
                                    pct = 0.05)) +
    # x err bar is too small to notice so omit
    geom_text(aes(label = n.f.total),
              hjust = 1.25, vjust = -1.3,
              show.legend = FALSE) + 
    scale_color_brewer(palette = "Dark2") +
    facet_wrap(~ mate.type)
}

dfs_tents_ss$eggs_nocol %>%
  filter(year == 2023) %>%
  .plotfn() +
  labs(caption = "2023") 

dfs_tents_ss$eggs_nocol %>%
  filter(year == 2025) %>%
  .plotfn() +
  labs(caption = "2025")
```

## hatch+laid effect of col bugs in 2025
```{r}
## testing effect of including the col or not for 2025
.plotfn <- function(x){
  x %>%
   FilterForLabEggs() %>%
    ### SPECIFIC FOR THESE PLOTS ###
    filter(mate.type == "within",
           #mate.trt == 260
           ) %>%
    ###############################
   ggplot(aes(y = p.eggs.hatched, x = n.eggs.coll,
             col = mate.trt, 
             shape = mate.col
             )) +
  geom_point(size = 2) +
    geom_text(aes(label = n.f.total),
            hjust = 1.25, vjust = -1.3, show.legend = FALSE) + 
  geom_errorbar(aes(ymax = p.eggs.hatched + se.eggs.hatched,
                    ymin = p.eggs.hatched - se.eggs.hatched),
                width = CalcErrWd(x = dfs_tents_ss$eggs_nocol$n.eggs.coll,
                                  pct = 0.025)
                ) +
  facet_wrap(~mate.type) +
    scale_color_brewer(palette = "Dark2") +
    #ylim(c(0, 0.58)) + #### to keep axes same for these plots
    labs(shape = "sex of col bug")
}

p1 <- 
  dfs_tents_ss$eggs_nocol %>%
  mutate(mate.col = "na") %>%
  filter(year == "2025") %>%
  .plotfn() +
  labs(caption = "mate.type and mate.pop = lab for col") +
  scale_shape_manual(values = 16) +
  guides(shape = FALSE)

p2 <- 
dfs_tents_ss$eggs_matecol %>%
  mutate(mate.col = replace_na(mate.col, "na")) %>%
  filter(year == "2025") %>%
  .plotfn() +
  labs(caption = "mate.type = col") +
  scale_shape_manual(values = c(17, 15, 16)) +
  guides(shape = FALSE)

p3 <- 
dfs_tents_ss$eggs_allcol %>%
  mutate(mate.col = replace_na(mate.col, "na")) %>%
  filter(year == "2025") %>%
  .plotfn() +
  labs(caption = "mate.type and mate.pop for\nlab/col are distinct") +
  scale_shape_manual(values = c(3, 17, 15, 16))

p1
p2
p3
```
```{r}
# patchworking...
(p1 + p2 + p3) +
  plot_layout(guides = "collect", axes = "collect",
              #ncol = 1, nrow = 3, widths = c(1:2)
              ) &
  #guides(col = guide_legend(nrow = 2, byrow = TRUE)) &
  ylim(c(0, 0.58)) &
  theme(legend.position = "top", #legend.box = "vertical",
        legend.margin = margin()) &
  
  plot_annotation(title = "effect of parsing col ctrls") 

```

## eggs laid

```{r}
.plotfn <- function(x){
  x %>%
  FilterForLabEggs() %>% 
  ggplot(aes(#y = avg.coll.perf, 
             y = avg.sqrt.coll.perf,
             x = mate.trt,
             lty = mate.hs, shape = mate.hs,
             group = mate.hs,
             col = mate.hs
             # shape = mate.hs, lty = mate.type,
             # group = interaction(mate.hs, mate.type)
  )) + 
  # very overwhelming w error bars lol
  # geom_errorbar(aes(ymax = avg.coll.perf + se.coll.perf,
  #                   ymin = avg.coll.perf - se.coll.perf,),
  #               lty = "solid", width = 0.5) +
  # geom_errorbar(aes(ymax = avg.sqrt.coll.perf + se.sqrt.coll.perf,
  #                   ymin = avg.sqrt.coll.perf - se.sqrt.coll.perf),
  #               lty = "solid", width = 0.5) +
  # geom_text(aes(label = n.f.total),
  #           vjust = -0.5, hjust = -0.5, position = "jitter") +
  # geom_text(aes(label = paste0(n.cages.total, "C, ", n.f.total, "F")),
  #           vjust = -0.5, hjust = -0.5, 
  #           #position = "jitter"
  #           ) +
  geom_point(size=2) + geom_line() +
  facet_grid(~year) +
  theme_bw() +
  #scale_shape_manual(values = c(2, 0, 16)) +
  scale_color_brewer(palette = "Dark2") +
  #scale_linetype_manual(values = c(3, 2, 1)) +
  labs(col = "treated sex", lty = "treated sex", shape = "treated sex",
       caption = "mean±se; lab only",
       y = "sqrt [eggs laid per female]", x = "treatment")
}

# connect "btwn" trts to 26-26
.plotfn2 <- function(x){
    list(
      geom_line(data = x %>%
                  #FilterForLabEggs(dfs_tents_ss$eggs_nocol) %>%
                  filter(trt.f %in% c(260, 419), mate.hs %in% c("both", "f"),
                         trt.m != 419) %>%
                  select(-mate.trt) %>%
                  rename(mate.trt = trt.f) %>% mutate(mate.hs = "f") #%>% View()
                #, color = "black"
                , aes(group = mate.hs), show.legend = FALSE,
                ),
        geom_line(data = x %>%
                    #FilterForLabEggs(dfs_tents_ss$eggs_nocol) %>%
                    filter(trt.m %in% c(260, 419), mate.hs %in% c("both", "m"),
                           trt.f != 419) %>%
                    select(-mate.trt) %>%
                    rename(mate.trt = trt.m) %>% mutate(mate.hs = "m") #%>% View()
                  ,
                  #aes(group = mate.trt), 
                  show.legend = FALSE)
      )
}

dfs_tents_ss$eggs_nocol %>%
  .plotfn() +
  .plotfn2(FilterForLabEggs(dfs_tents_ss$eggs_nocol)) +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_tents_ss$eggs_nocol %>%
  filter(mate.trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))
  
```
## eggs hatched

```{r}
.plotfn <- function(x){
  x %>%
  FilterForLabEggs() %>% 
  ggplot(aes(y = p.hatch,
             x = mate.trt,
             lty = mate.hs, shape = mate.hs,
             group = interaction(mate.hs),
             col = mate.hs
  )) + 
  geom_errorbar(aes(ymax = p.hatch + se.hatch,
                    ymin = p.hatch - se.hatch,),
                lty = "solid", width = 0.25) +
      # geom_text(aes(label = paste0(n.cages.total, "C,", n.f.total, "F")),
      #       vjust = -0.5, hjust = -0.5, size = 3
      #       #position = "jitter"
      #       ) +
  geom_point(size=2) + geom_line() +
  facet_grid(~year) +
  theme_bw() +
  #scale_shape_manual(values = c(2, 0, 16)) +
  scale_color_brewer(palette = "Dark2") +
  #scale_linetype_manual(values = c(3, 2, 1)) +
  labs(col = "treated sex", lty = "treated sex", shape = "treated sex",
       caption = "bars = se; lab only",
       y = "proportion eggs hatched", x = "treatment")
}

dfs_tents_ss$eggs_nocol %>%
  .plotfn() +
  .plotfn2(FilterForLabEggs(dfs_tents_ss$eggs_nocol)) +
  scale_x_discrete(labels = c("26-26", "40-19", "40-26", "40-33"))

dfs_tents_ss$eggs_nocol %>%
  filter(mate.trt != 260) %>%
  .plotfn() +
  scale_x_discrete(labels = c("40-19", "40-26", "40-33"))
```


