---
title: "ntw 2025 wrangling"
date: "2025-11-29"
---

# # preamble & loading

- data wrangling for ntw 2025 data here
- data gets purled for wrangling later (update script as needed)

```{r set paths, eval=FALSE, purl=FALSE}
# run if things arent working
here::i_am("2025/ntw/data-wrangle.Rmd")
library(here)
source(here("set-paths.R"))
```

```{r purl, eval=FALSE, purl=FALSE}
# rerun to update .R script (save .Rmd first)
knitr::purl("data-wrangle.Rmd", 
            here(bin_paths$y25$ntw, "/R/wrangle-data.R"))
```

```{r about}
# purled wrangling code for ntw figs.
# compiles 2023-25 development and tent summary statistics.
```


```{r load libs and data, message=FALSE}
# libraries
library(tidyverse)
library(here)

# objects
source(here("set-paths.R"))
source(here(bin_paths$y25$ntw, "/utils/data-wrangle.R")) 
source(here(bin_paths$y25$ntw, "/R/tidy-data.R"))
```


# # development stuff

```{r}
dfs_dev_ss <- list()
```



## sup proportions

```{r supernumerary development}
# TODO maybe a: dfs_wider with TT, pcts, outcomes, etc... sublists? see 2024 ntw wrangle Rmd

dfs_dev_ss <- list(
  sup_outcomes = 
    dfs_tidy$wide %>% 
    filter(is.pup != 2) %>%
    group_by(year, pop, diet, trt) %>%
    summarise(N = n(),
              surv_tot = sum(is.pup == 1),
              surv_0th = sum(is.pup == 1 & is.na(sup)),
              surv_6th = sum(is.pup == 1 & sup == 6, na.rm = TRUE),
              surv_7th = sum(is.pup == 1 & sup == 7, na.rm = TRUE),
              surv_8th = sum(is.pup == 1 & sup == 8, na.rm = TRUE),
              died_tot = sum(is.pup == 0),
              died_0th = sum(is.pup == 0 & is.na(sup)),
              died_6th = sum(is.pup == 0 & sup == 6, na.rm = TRUE),
              died_7th = sum(is.pup == 0 & sup == 7, na.rm = TRUE),
              died_8th = sum(is.pup == 0 & sup == 8, na.rm = TRUE),
              ) %>%
      pivot_longer(cols = starts_with(c("surv", "died")),
                 names_to = c("status", ".value"),
                 names_sep = "_") %>%
    mutate(not = N - tot,
           across(c("not", "0th", "6th", "7th", "8th"), ~ ./N, .names = "p_{.col}")) %>%
      rename_with(~ paste0("n_", .x), matches("^(not)|^(\\dth)")) %>%
        pivot_longer(cols = starts_with(c("n_", "p_")),
                 names_to = c(".value", "sup"), names_sep = "_") %>%
    mutate(sup = gsub(sup, pattern = "th", replacement = ""),
           sup = case_when(sup == "not" & status == "surv" ~ "died",
                           sup == "not" & status == "died" ~ "survived",
                           TRUE ~ as.character(sup),
                           ))
)

# nts: for when the names were n_status_stage: 
# names_pattern = "(n_[a-z]*)_(\\d*[a-z]*)")
    
```

## development outcomes

```{r dev ss custom fn}
.CalcDevSS <- function(x){
  x %>%
    mutate(log.mass = log(mass)) %>%
    summarise(n = n(),
              avg.logmass = mean(log.mass, na.rm = TRUE),
              se.logmass = se(log.mass),
              avg.mass = mean(mass, na.rm = TRUE),
              se.mass = se(mass),
              avg.tt = mean(tt, na.rm = TRUE),
              se.tt = se(tt))
}
```


```{r overall development}
dfs_dev_ss <- list_modify(
  dfs_dev_ss,
  dev_outcomes_wpmd =
    dfs_tidy$long %>% 
    group_by(year, pop, diet, trt, instar) %>%
    .CalcDevSS(),
  
  dev_outcomes_nopmd =
    dfs_tidy$long %>% 
    filter(is.pup != 0 | is.na(is.pup)) %>%
    group_by(year, pop, diet, trt, instar) %>%
    .CalcDevSS(),
  
  ad_dev = 
    dfs_tidy$long %>%
    filter(instar %in% c("pupa", "eclose", "surv")) %>%
    group_by(year, pop, diet, trt, instar) %>%
    mutate(mass = mass/1000) %>%
    .CalcDevSS(),
  
  ad_dev_bysex = 
    dfs_tidy$long %>%
    filter(instar %in% c("pupa", "eclose", "surv"), !is.na(sex)) %>%
    group_by(year, pop, diet, trt, sex, instar) %>%
    mutate(mass = mass/1000) %>%
    .CalcDevSS()
)
```

## survival props

```{r}
dfs_dev_ss <- list_modify(
  dfs_dev_ss,
    surv_outcomes =
    dfs_tidy$wide %>%
    filter(is.pup != 2) %>%
    group_by(year, pop, diet, trt) %>%
    summarise(n = n(),
              prop.pup = sum(is.pup == 1)/n,
              se.pup = se.prop(prop.pup, n))
)
```


# # tents + egg stuff

  
```{r}
dfs_tents_ss <- list()
```

```{r eggs ss custom fn}
.CalcTentsSS <- function(x){
  x %>%
  #dfs$tents %>% # for testing
    # first get counts at cage level
  group_by(across(c("year", "cage", starts_with(c("mate", "trt"))))) %>%
  summarise(
    #n = n(), # number of days a tent existed for
    n.f = sum(f.added),
    n.viable = sum(eggs.fert),
    n.coll = sum(eggs.coll),
    n.hatch = sum(eggs.hatched),
    n.coll.perf = n.coll/n.f,
    sqrt.coll.perf = sqrt(n.coll.perf)
  ) %>% 
  #filter(mate.type == "within", mate.pop == "lab", mate.trt == 426) %>% 
  #View()
  ungroup() %>%
      # then get counts at mate type level
  group_by(across(c("year", starts_with(c("mate", "trt"))))) %>%
  summarise(
    n.cages.total = n(),
    n.f.total = sum(n.f),
    
    # these look rly bad compared to the daily level LOL
    avg.coll.total = mean(n.coll),
    se.coll.total = se(n.coll),
    avg.coll.perf = mean(n.coll.perf),
    se.coll.perf = se(n.coll.perf),
    
    avg.sqrt.coll.perf = mean(sqrt.coll.perf),
    se.sqrt.coll.perf = se(sqrt.coll.perf),
    #p.hatch = n.hatch.total/n.viable.total, 
      # will get prop.hatch per tent if not sum()'d beforehand
    p.hatch = sum(n.hatch)/sum(n.viable), 
    se.hatch = se.prop(p.hatch, sum(n.viable))
            ) %>%
  #filter(mate.type == "within", mate.pop == "lab", mate.trt == 426) %>%
  mutate(across(.cols = everything(), 
                ~ replace(.x, is.nan(.x), NA))) #%>% View()
}
```
```{r}
# not correct,,,
# .CalcTentsSS <- function(x){
#   x %>%
#     # TODO:FIX i feel liek this is in the wrong place LOL... (based off the piddly #s..)
#   mutate(eggs.perf = eggs.coll/f.curr,
#          eggs.perf = case_when(!is.finite(eggs.perf) ~ 0,
#                                TRUE ~ as.numeric(eggs.perf))) %>% #View() ## ????
#     group_by(year, # omit if theres only 1 yr in the df
#              across(starts_with("mate"))) %>%
#     # maybe mut and then just distinct by new columns instead of summary?
#     summarise(n.cages.total = 
#                 n_distinct(across(c("cage", starts_with("mate")))),
#               n.f.total = sum(f.added), 
#               
#               # viable + non-viable eggs
#               n.eggs.viable = sum(eggs.fert),
#               se.eggs.viable = se(eggs.fert),
#               n.eggs.coll = sum(eggs.coll),
#               se.eggs.coll = se(eggs.coll),
#               #   # check how i did this in 2023?
#               # n.eggs.perf = n.eggs.coll/n.f.total, # do outside?
#               # avg.eggs.perf = mean(n.eggs.perf),
#               # se.eggs.perf = se(n.eggs.perf),
#               avg.eggs.perf = mean(eggs.perf),
#               se.eggs.perf = se(eggs.perf),
#               
#               # hatching (viable eggs only)
#               n.eggs.hatched = sum(eggs.hatched),
#               p.eggs.hatched = n.eggs.hatched/n.eggs.viable,
#               se.eggs.hatched = se.prop(p.eggs.hatched, n.eggs.viable),
#               #   # check how i did this in 2023?
#               # p.eggs.hatchedperf = p.eggs.hatched/n.f.total,
#               # se.eggs.hatchedperf = se.prop(p.eggs.hatchedperf, n.eggs.viable)
#     ) %>%
#     mutate(across(starts_with(c("n.", "p.", "se.", "avg.")), 
#                   replace_na, 0))
# }
```


## ss calcs

```{r eggs ss calcs}
# 2025-12-10: have variations on handling colony bugs for now...

dfs_tents_ss <- list(
  # treat all col like lab expt bugs
  eggs_nocol = dfs_tidy$tents %>%
    select(-mate.col) %>% 
    mutate(mate.pop = case_when(mate.pop == "col" ~ "lab",
                                TRUE ~ as.character(mate.pop))) %>% 
    .CalcTentsSS(),
  
  # treats col like lab expt bugs, but notes which sex was the col
  eggs_matecol = dfs_tidy$tents %>%
    mutate(mate.pop = case_when(mate.pop == "col" ~ "lab",
                                TRUE ~ as.character(mate.pop)),
           mate.col = na_if(mate.col, "both")) %>%
    .CalcTentsSS(),
  
  # retains all indicators of col status (population + affected sex)
  eggs_allcol = dfs_tidy$tents %>%
    .CalcTentsSS()
)
```



# RData export

## TODO
- need sth seperate for stats wrangle?

```{r}
rm(dfs_tidy,
   se, se.prop)
```

