---
title: "2025 ntw cleaning"
date: "2025-11-26"
---

# preamble

prepping ntw 2025 data for wrangling

final code is purled to a `.R` script, rerun `purl` step as needed to update the wrangling for analyses

```{r eval=FALSE, include=FALSE, purl=FALSE}
# rerun this chunk if purled script needs to be updated
knitr::purl("data-cleaning.Rmd", "cleaning_p.R")

knitr::purl("data-cleaning.Rmd", paste0(here(bin_paths$y25$ntw),                                   "/archive/cleaning/", format(Sys.time(), "%y%m%d"), "_cleaning_p.R"))
```

# load libs & pkgs

```{r about}
# cleaning/ntw-2025.R

# knitted wrangling code for 2025 ntw dev figs/analyses.
# source() this in corresponding analysis scripts.

# note that this script has mostly been superseded for the 23v24 analyses and
# is meant to be more of a reference!
```

```{r load libs}
library(tidyverse)

here::i_am("2025/ntw/data-cleaning.Rmd")
library(here)

source(here::here("set-paths.R"))

source(here::here(bin_paths$y25$ntw, "utils.R"))
```


# larval data

## loading
```{r load larval data}
dfs_imported <- list(
  y23 = read.csv(here::here(bin_paths$y23$data, "clean-ntw.csv"), header = TRUE) %>% mutate(year = 2023),
  y24 = read.csv(here::here(bin_paths$y24$data, "ntw.csv"), header = TRUE) %>% mutate(year = 2024),
  y25 = read.csv(here::here(bin_paths$y25$ntwdata, "clean-larva.csv"), header = TRUE) %>% mutate(year = 2025)
  )
```

## standardising

```{r filtering and column cleanup}
dfs_filtered <- list(
  
  y23 = dfs_imported[[1]] %>%
    filter(instar.enter == "hatch",
           pop %in% c("field", "lab"),
           !(treatment %in% c("ctrl", "267", "330")),
           reason.ignore != "lost" | is.na(reason.ignore),
           ) %>%
    rename(id = ID,
           jdate.LPI = jdate.LP,
           trt = treatment,
           cohort = expt.group) %>%
    select(-c(starts_with(c("date", "h.", "if.")), ends_with("2nd"), 
              "instar.enter",  "jdate.collected", "jdate.enter", 
              "jdate.stuck", "jdate.15", "jdate.died",
              "parent.tent", "src", "trt.stage", "grp.trt")),

  y24 = dfs_imported[[2]] %>%
    filter(instar.enter == "hatch") %>%
    select(-c("trt.type", "jdate.enter", "instar.enter", ends_with("2nd"))),
  
  y25 = dfs_imported[[3]] %>%
    filter(is.na(species),
           !(notes.ignore == "empty") | is.na(notes.ignore)) %>%
    rename(pop = population,
           trt = treatment) %>%
    select(-c("species", "jdate.enter", "instar.enter", ends_with("2nd")))
)

```

```{r standardising values}
# stdise column types
dfs_stdised <- lapply(dfs_filtered, \(x){
  x %>%
  mutate(trt = as.numeric(trt),
         id = as.numeric(id),
         across(starts_with("jdate"), as.numeric))
})

# recoding + adding missing columns
# 2023: redo trt values, survival coding/notes, sup coding; add trt group
dfs_stdised[[1]] <- dfs_stdised[[1]] %>% 
  mutate(mass.8th = NA, jdate.8th = NA,
         trt = case_when(trt == 337 ~ 426,
                         TRUE ~ trt),
         trt.group = case_when(pop == "lab" & diet == "TB" ~ 1000,
                               pop == "lab" & diet == "LD" ~ 2000,
                               TRUE ~ 100),
         fate.dev = case_when(reason.ignore %in% c("wet diet", "accidental", "hot larva", "cut") | final.fate %in% c("accidental", "culled") ~ "other",
                              !is.na(jdate.eclose) ~ "ec",
                              !is.na(jdate.pupa) | !is.na(jdate.LPI) ~ "pup",
                              !is.na(jdate.pmd) ~ "pmd"),
         jdate.culled = case_when(final.fate %in% c("accidental", "culled") ~ jdate.exit),
  ) %>%
  select(-c("final.fate", "reason.ignore"))

# 2024: redo survival coding, trt group
dfs_stdised[[2]] <- dfs_stdised[[2]] %>% 
  mutate(jdate.LPI = NA, jdate.exit = NA, 
         trt.group = case_when(id < 1000 ~ 100,
                               id > 2000 ~ 2000,
                               TRUE ~ 1000),
         fate.dev = case_when(!is.na(jdate.culled) | surv.outcome == 2  ~ "other",
                              !is.na(jdate.eclose) ~ "ec",
                              !is.na(jdate.pupa) ~ "pup",
                              !is.na(jdate.pmd) ~ "pmd"),
         ) %>%
  select(-"surv.outcome")

# 2025: redo survival coding/notes; add tempts
dfs_stdised[[3]] <- dfs_stdised[[3]] %>% 
  mutate(fate.dev = case_when(!is.na(jdate.culled) | !is.na(notes.ignore)  ~ "other",
                              !is.na(jdate.surv) ~ "ec",
                              !is.na(jdate.pupa) | !is.na(jdate.LPI) ~ "pup",
                              !is.na(jdate.pmd) ~ "pmd"),
         meanT = case_when(trt == 260 ~ 26,
                           trt == 419 ~ 29.5,
                           trt == 426 ~ 33,
                           trt == 433 ~ 36.5),
         flucT = case_when(trt == 260 ~ 0,
                           trt == 419 ~ 10.5,
                           trt == 426 ~ 7,
                           trt == 433 ~ 3.5),
         maxT = case_when(trt == 260 ~ 26,
                          TRUE ~ 40),
         minT = case_when(trt == 260 | trt == 426 ~ 26,
                          trt == 419 ~ 19,
                          trt == 433 ~ 33)) %>%
  filter(!is.na(status)) %>%
  select(-c(starts_with("notes"), "status"))


# redo survival, sup coding (counts after reaching 5th);
# fix exit dates
dfs_stdised <- lapply(dfs_stdised, \(x){
  x %>%
    mutate(fate.code = case_when(fate.dev %in% c("ec", "pup") ~ 1,
                                 fate.dev == "pmd" ~ 0,
                                 fate.dev == "other" ~ 2),
           sup = case_when(!is.na(jdate.8th) ~ 8,
                           !is.na(jdate.7th) ~ 7,
                           !is.na(jdate.6th) ~ 6,
                           #!is.na(jdate.5th) ~ 5,
                           #FALSE ~ as.numeric(sup)
                            ),
           jdate.exit = case_when(!is.na(jdate.culled) ~ as.numeric(jdate.culled),
                                  !is.na(jdate.LPI) ~ as.numeric(jdate.LPI),
                                  !is.na(jdate.pupa) ~ as.numeric(jdate.pupa),
                                  !is.na(jdate.pmd) ~ as.numeric(jdate.pmd),
                                   FALSE ~ as.numeric(jdate.exit)
                                   )
    )
}) 

```

## export

```{r}
# 2025-11-28 TODO: jdate.surv and id.cage are not applied consistently so just drop for now.. but will need later for adult stuff LOL

# combine dfs and remove short-lived things
dfs <- list(wide = data.table::rbindlist(dfs_stdised, fill = TRUE) %>%
              filter(jdate.exit - jdate.hatch > 1 | is.na(jdate.exit - jdate.hatch)) %>%
              select(-c("id.cage", "jdate.surv"))
)


  # TODO could drop jdate column maybe?
dfs <- list_modify(dfs,
                   long = dfs$wide %>% 
                     mutate(tt.3rd = jdate.3rd - jdate.hatch,
                            tt.4th = jdate.4th - jdate.hatch,
                            tt.5th = jdate.5th - jdate.hatch,
                            tt.6th = jdate.6th - jdate.hatch,
                            tt.7th = jdate.7th - jdate.hatch,
                            tt.8th = jdate.8th - jdate.hatch,
                            tt.wander = jdate.wander - jdate.hatch,
                            tt.pupa = jdate.pupa - jdate.hatch,
                            tt.eclose = jdate.eclose - jdate.hatch) %>%
                     pivot_longer(cols = starts_with(c("jdate", "mass", "tt")),
                                  names_to = c(".value", "instar"),
                                  values_drop_na = TRUE,
                                  names_pattern = ("([a-z]*\\d*)\\.(\\d*[a-z]*)")) %>%
                     
                     # drop empty dev times but keep masses
                     mutate(tt = case_when(is.na(tt) & !is.na(mass) ~ 999,
                                           TRUE ~ as.numeric(tt))) %>%
                     drop_na(tt) %>%
                     mutate(tt = na_if(tt, 999)) #%>% 
                     #filter(tt > 0 | is.na(tt)) # temporary LOL until reimport 2025 data
) 
```

# adult data

## loading

```{r}
# add yr later? breaks later on bc of the pivoting

dfs_imported <- list(
  ad25 = read.csv(here::here(bin_paths$y25$ntwdata, "clean-adults.csv"), header = TRUE) %>% mutate(year = 2025),
  coll25 = read.csv(here::here(bin_paths$y25$ntwdata, "clean-coll.csv"), header = TRUE) %>% mutate(year = 2025),
  hatch25 = read.csv(here::here(bin_paths$y25$ntwdata, "clean-hatch.csv"), header = TRUE) %>% mutate(year = 2025)
)
```

## setup cage info
```{r}
# dfs modified..?
dfs_tents <- list(
  
  # cage info
  info = dfs_imported[["ad25"]] %>%
    pivot_wider(names_from = "sex", values_from = "pop") %>%
    select(trt, cage, f) %>% rename(trt.f = trt) %>%
    drop_na(f) %>% distinct() %>%
    merge(
      dfs_imported[["ad25"]] %>% pivot_wider(names_from = "sex", values_from = "pop") %>% select(trt, cage, m) %>% rename(trt.m = trt) %>% 
        drop_na(m) %>% distinct(), 
      all = TRUE
    ) %>% 
    drop_na(cage) %>%
    rename(pop.f = f, pop.m = m) %>%
    mutate(mate.type = case_when(trt.f == trt.m ~ "within",
                                 trt.f != trt.m ~ "between",
                                 is.na(trt.m) ~ "virgin f"),
           mate.pop = case_when(mate.type == "within" | is.na(pop.m) ~ pop.f,
                                mate.type == "between" & !(pop.f == "field" | pop.m == "field") ~ "lab"), 
           mate.trt = case_when(mate.type == "within" | is.na(trt.m) ~ trt.f,
                                mate.type == "between" & trt.f > trt.m ~ trt.f,
                                mate.type == "between" & trt.m > trt.f ~ trt.m),
           mate.col = case_when(pop.f == "col" | pop.m == "col" ~ "x"),
           mate.hs = case_when(trt.f > trt.m ~ "f",
                               trt.m > trt.f ~ "m"),
           #mate.nom = case_when(is.na(trt.m) ~ "x")
           ) %>%
    filter(!(cage == "A8" & pop.m == "lab"),
           !(cage == "B5" & (pop.f == "col" | pop.m == "col"))),
  
  # cage timelines (mating pair info)
  events = dfs_imported[["ad25"]] %>%
    pivot_longer(starts_with("jdate"),
                 names_to = c(".value", "event"),
                 names_sep = "\\.") %>% 
    drop_na("jdate") %>% 
    group_by(cage, jdate) %>%
    summarise(f.added = sum(sex == "f" & event == "added"),
              m.added = sum(sex == "m" & event == "added"),
              f.removed = sum(sex == "f" & event == "removed"),
              m.removed = sum(sex == "m" & event == "removed")) %>%
    drop_na(cage)
)

# cage timelines (egg collection info)
dfs_tents$events <-
  dfs_imported[["coll25"]] %>%
  rename(jdate = jdate.collected) %>%
  merge(., dfs_tents$events, all = TRUE) %>%
  merge(., dfs_tents$info %>% select(c("cage", starts_with("mate"))), all = TRUE, by = c("cage")) %>%
  mutate(across(starts_with(c("eggs", "f.", "m.")), replace_na, 0))
```

## setup egg collection info
```{r}
# ## DRAFT
# # do math
# tents <- dfs_tents$events[order(dfs_tents$events$cage, dfs_tents$events$jdate),] %>% split(f = dfs_tents$events$cage)
# 
# #testing: C14, C4
# test <- dfs_tents$events[dfs_tents$events$cage == "C14", ]
# 
# test %>%
#   select(-c(cage, starts_with(c("mate")))) %>% # readability
#   
#   ### BELOW INTO LAPPLY
#   arrange(jdate) %>%
#   mutate(f.diff = lag(f.added, default = 0) - lag(f.removed, default = 0),
#          f.curr = 0,
#          f.curr = cumsum(f.diff + f.curr),
#          m.diff = lag(m.added, default = 0) - lag(m.removed, default = 0),
#          m.curr = 0,
#          m.curr = cumsum(m.diff + m.curr),
#          eggs.exclude = case_when(f.curr <= 0 & m.curr > 0 ~ as.numeric(eggs.collected + eggs.exclude),
#                                   TRUE ~ as.numeric(eggs.exclude)),
#          eggs.collected = case_when(f.curr <= 0 & m.curr > 0 ~ 0,
#                                     TRUE ~ as.numeric(eggs.collected))) %>%
#   View()



### FINAL
dfs <- list_modify(
  dfs,
  tents = 
    dfs_tents$events[order(dfs_tents$events$cage, dfs_tents$events$jdate),] %>%
  split(f = dfs_tents$events$cage) %>% 
  lapply(., \(x){
  x %>%
    arrange(jdate) %>%
    mutate(f.diff = lag(f.added, default = 0) - lag(f.removed, default = 0),
           f.curr = 0,
           f.curr = cumsum(f.diff + f.curr),
           m.diff = lag(m.added, default = 0) - lag(m.removed, default = 0),
           m.curr = 0,
           m.curr = cumsum(m.diff + m.curr),
           # wrong logic..
           # eggs.exclude = case_when(f.curr <= 0 & m.curr >= 0 ~ as.numeric(eggs.collected + eggs.exclude),
           # TRUE ~ as.numeric(eggs.exclude)),
           # eggs.collected = case_when(f.curr <= 0 & m.curr > 0 ~ 0,
           #                            TRUE ~ as.numeric(eggs.collected)),
           eggs.exclude = case_when(mate.type == "virgin f" | 
                                      f.curr > 0 & m.curr == 0 ~ as.numeric(eggs.collected + eggs.exclude),
                                   TRUE ~ as.numeric(eggs.exclude)),
           eggs.collected = case_when(mate.type == "virgin f" | 
                                        f.curr > 0 & m.curr == 0 ~ 0,
                                      TRUE ~ as.numeric(eggs.collected)),
           eggs.coll = eggs.collected + eggs.exclude) %>%
    select(-ends_with(c(".removed", ".diff"))) %>%
      rename(eggs.fert = eggs.collected,
             eggs.unfert = eggs.exclude)
}) %>%
  rbindlist()
)
         
```






# cleanup
```{r remove intermediate objects}
rm(dfs_imported, dfs_filtered, dfs_stdised)
```

