---
title: "ntw 2025 cleaning"
date: "2025-11-24"
---

# 0. roadmap

1. load data & packages; pre-filtering
2. column formatting + rearrangement
3. save output into `2025/data/`

re-run script whenever the gsheets gets updated

LAST RUN: 2025-11-24


# 1. loading

## - data and packages
```{r message = FALSE}
#library(tidyr)
#library(purrr)
library(dplyr)
library(lubridate) # for handling time stuff
library(googlesheets4)

here::i_am("2025/ntw/cleaning.Rmd")
library(here)

source(here::here("set-paths.R"))
```

## - googlesheets import

```{r}
raw <- read_sheet("https://docs.google.com/spreadsheets/d/1rxZSI-8ubhMkeM2Sh1xNi5IKF0Vt_BDFItAg_Ak476M/edit?gid=1826657546#gid=1826657546", 
                  sheet = "ntw aug 2025",
                  col_types = "c",
                  #na = c("#VALUE!")
                  ) %>%
  drop_na(id)

data <- raw

```

# 2. column futzing

todo: filter out bad bugs? sub 1 day dead bugs? (in the wrangle?)


```{r}
# standardise format
data <- data %>%
  mutate(across(starts_with("date"), as.Date, format = "%m/%d/%Y"),
         across(c("id", starts_with("mass")), as.numeric))
```


```{r}
# consolidate exits; remove extra dates
data <- data %>%
  mutate(date.exit = case_when(!is.na(date.culled) ~ date.culled,
                               !is.na(date.LPI) ~ date.LPI,
                               !is.na(date.surv) ~ date.surv,
                               !is.na(date.pmd) ~ date.pmd))

# julian date conversions
data <- data %>%
  mutate(across(starts_with("date."), as.Date, "%j", .names = "j{.col}")) %>%
  # attempts at putting the new columns after the old ones sighs
  #relocate(sort(grep("^jdate", names(.), value = TRUE)), .after = starts_with("date"))
  #select(sort(names(.)))
  mutate(across(starts_with("jdate."), as.numeric))

```


# 3. saving output & tidying up

```{r}
# remove extra columns
export <- data %>%
  select(-c("location", "time.enter",
            starts_with(c("date.", "h.", "stuck", "notes.last")),
            "jdate.collected", "jdate.outby", "jdate.15",
            "if.fridge"))
```


```{r}
# setup
today <- format(Sys.time(), "%y%m%d-%H%M")
```

```{r}
# export
write.csv(raw, file = paste0(here(bin_paths$y25$ntwdata), "/archive/", today, "_raw.csv"), row.names = FALSE)
write.csv(export, file = paste0(here(bin_paths$y25$ntwdata), "/clean-working.csv"), row.names = FALSE)
```

```{r}
# remove troubleshooting objects
rm(today, raw, data, export)
```