---
title: "2025 ntw wrangling"
date: "2025-11-26"
---

# 0. preamble

wrangling data for 2025 ntw data

final code is purled to a `.R` script, rerun `purl` step as needed to update the wrangling for analyses

```{r eval=FALSE, include=FALSE, purl=FALSE}
#knitr::purl("wrangle.Rmd", "wrangle_p.R")
```

# 1. loading

```{r about}
# wrangle/ntw-2025.R

# knitted wrangling code for 2025 ntw dev figs/analyses.
# source() this in corresponding analysis scripts.

# note that this script has mostly been superseded for the 23v24 analyses and
# is meant to be more of a reference!
```

```{r load utils}
library(tidyverse)

here::i_am("2025/ntw/wrangle.Rmd")
library(here)

source(here::here("set-paths.R"))

source(here::here(bin_paths$y25$ntw, "utils.R"))
```

```{r load data}
dfs_imported <- list(
  y23 = read.csv(here::here(bin_paths$y23$data, "clean-ntw.csv"), header = TRUE) %>% mutate(year = 2023),
  y24 = read.csv(here::here(bin_paths$y24$data, "ntw.csv"), header = TRUE) %>% mutate(year = 2024),
  y25 = read.csv(here::here(bin_paths$y25$ntwdata, "clean-working.csv"), header = TRUE) %>% mutate(year = 2025)
  )
```

# 2. standardising

custom fns: `StandardiseColTypes`, `CodeDevOutcomes`

```{r filtering and column cleanup}
dfs_filtered <- list(
  
  y23 = dfs_imported[[1]] %>%
    filter(instar.enter == "hatch",
           pop %in% c("field", "lab"),
           treatment != "ctrl",
           reason.ignore != "lost" | is.na(reason.ignore)
           ) %>%
    rename(id = ID,
           jdate.LPI = jdate.LP,
           trt = treatment,
           cohort = expt.group) %>%
    select(-c(starts_with(c("date", "h.", "if.")), ends_with("2nd"), 
              "instar.enter",  "jdate.collected", "jdate.enter", 
              "jdate.stuck", "jdate.15", "jdate.died",
              "parent.tent", "src", "trt.stage", "grp.trt")),

  y24 = dfs_imported[[2]] %>%
    filter(instar.enter == "hatch") %>%
    select(-c("trt.type", "jdate.enter", "instar.enter", ends_with("2nd"))),
  
  y25 = dfs_imported[[3]] %>%
    filter(is.na(species),
           !(notes.ignore == "empty") | is.na(notes.ignore)) %>%
    rename(pop = population,
           trt = treatment) %>%
    select(-c("species", "jdate.enter", "instar.enter", ends_with("2nd")))
)

```

```{r standardising values}
# stdise column types
dfs_stdised <- lapply(dfs_filtered, \(x){
  x %>%
  mutate(trt = as.numeric(trt),
         id = as.numeric(id),
         across(starts_with("jdate"), as.numeric))
})

# recoding + adding missing columns
# 2023: redo trt values, survival coding/notes, sup coding; add trt group
dfs_stdised[[1]] <- dfs_stdised[[1]] %>% 
  mutate(mass.8th = NA, jdate.8th = NA,
         trt = case_when(trt == 337 ~ 426,
                         TRUE ~ trt),
         trt.group = case_when(pop == "lab" & diet == "TB" ~ 1000,
                               pop == "lab" & diet == "LD" ~ 2000,
                               TRUE ~ 100),
         fate.dev = case_when(reason.ignore %in% c("wet diet", "accidental", "hot larva", "cut") | final.fate %in% c("accidental", "culled") ~ "other",
                              !is.na(jdate.eclose) ~ "ec",
                              !is.na(jdate.pupa) | !is.na(jdate.LPI) ~ "pup",
                              !is.na(jdate.pmd) ~ "pmd"),
         jdate.culled = case_when(final.fate %in% c("accidental", "culled") ~ jdate.exit),
  ) %>%
  select(-c("final.fate", "reason.ignore"))

# 2024: redo survival coding, trt group
dfs_stdised[[2]] <- dfs_stdised[[2]] %>% 
  mutate(jdate.LPI = NA, jdate.exit = NA, 
         trt.group = case_when(id < 1000 ~ 100,
                               id > 2000 ~ 2000,
                               TRUE ~ 1000),
         fate.dev = case_when(!is.na(jdate.culled) | surv.outcome == 2  ~ "other",
                              !is.na(jdate.eclose) ~ "ec",
                              !is.na(jdate.pupa) ~ "pup",
                              !is.na(jdate.pmd) ~ "pmd"),
         ) %>%
  select(-"surv.outcome")

# 2025: redo survival coding/notes; add tempts
dfs_stdised[[3]] <- dfs_stdised[[3]] %>% 
  mutate(fate.dev = case_when(!is.na(jdate.culled) | !is.na(notes.ignore)  ~ "other",
                              !is.na(jdate.surv) ~ "ec",
                              !is.na(jdate.pupa) | !is.na(jdate.LPI) ~ "pup",
                              !is.na(jdate.pmd) ~ "pmd"),
         meanT = case_when(trt == 260 ~ 26,
                           trt == 419 ~ 29.5,
                           trt == 426 ~ 33,
                           trt == 433 ~ 36.5),
         flucT = case_when(trt == 260 ~ 0,
                           trt == 419 ~ 10.5,
                           trt == 426 ~ 7,
                           trt == 433 ~ 3.5),
         maxT = case_when(trt == 260 ~ 26,
                          TRUE ~ 40),
         minT = case_when(trt == 260 | trt == 426 ~ 26,
                          trt == 419 ~ 19,
                          trt == 433 ~ 33)) %>%
  filter(!is.na(status)) %>%
  select(-c(starts_with("notes"), "status"))


# redo survival, sup coding (counts after reaching 5th);
# fix exit dates
dfs_stdised <- lapply(dfs_stdised, \(x){
  x %>%
    mutate(fate.code = case_when(fate.dev %in% c("ec", "pup") ~ 1,
                                 fate.dev == "pmd" ~ 0,
                                 fate.dev == "other" ~ 2),
           sup = case_when(!is.na(jdate.8th) ~ 8,
                           !is.na(jdate.7th) ~ 7,
                           !is.na(jdate.6th) ~ 6,
                           #!is.na(jdate.5th) ~ 5,
                           #FALSE ~ as.numeric(sup)
                            ),
           jdate.exit = case_when(!is.na(jdate.culled) ~ as.numeric(jdate.culled),
                                  !is.na(jdate.LPI) ~ as.numeric(jdate.LPI),
                                  !is.na(jdate.pupa) ~ as.numeric(jdate.pupa),
                                  !is.na(jdate.pmd) ~ as.numeric(jdate.pmd),
                                   FALSE ~ as.numeric(jdate.exit)
                                   )
    )
}) 

```




```
