---
title: "02-wrangle/plates"
date: "2025-02-27"
---

# 0. preamble

wrangling data from molecular assays

final code is purled to a `.R` script, manually rerun `purl()` as needed to update the wrangling script for analyses

```{r eval=FALSE, include=FALSE, purl=FALSE}
knitr::purl("plates.Rmd", "plates_p.R")
```


# 1. loading & defining

```{r about}
# wrangle/plates.R

# knitted wrangling code for plate data
# source() this in corresponding analysis scripts.
```

```{r load utils}
library(tidyverse)

here::i_am("2024/02-wrangle/plates.Rmd")
library(here)

source(here::here("set-paths.R"))
```

```{r load data}
sod <- list()

sod <- list_assign(sod, 
                   pre = read_csv(here(bin_paths24$data, "plates", "250205_sod redo", 
                                  "lh blank 25-02-05 13-13-21.csv"), 
                                  col_types = c("c", "c", "n"), skip = 5),
                   post = read_csv(here(bin_paths24$data, "plates", "250205_sod redo",
                                  "lh post 25-02-05 13-48-00.csv"),
                                  col_types = c("c", "c", "n"), skip = 5)
                   )

```



# 2. do stuff

## - plate wrangling and blanking

```{r merge dfs}
sod$pre <- rename(sod$pre, abs.pre = "Raw Data (450)") #mutate(sod$pre, read = "pre")
sod$post <- rename(sod$post, abs.post = "Raw Data (450)") #mutate(sod$post, read = "post")

sod <- list_assign(sod, merge = merge(sod$pre, sod$post, all = TRUE))

sod$merge <- sod$merge %>%
  rename(id = "Well",
         type = "Content") %>%
  filter(!(id %in% c("A03", "B02", "C02", "E02", "G02", "H01"))) # removing bad stds
```

```{r edit values}
sod <- list_assign(sod, all = sod$merge %>%
                     mutate(id.row = str_sub(id, 1, 1),
                            id.col = as.numeric(str_sub(id, 2, 3), .after = "id")) %>%
                     mutate(type = case_when(id.col < 4 | id %in% c("G08", "G09") ~ "std",
                                             TRUE ~ "unk"),
                            sod.cxn = case_when(id.row == "A" & id.col < 4 ~ 4,
                                            id.row == "B" & id.col < 4 ~ 2,
                                            id.row == "C" & id.col < 4 ~ 1,
                                            id.row == "D" & id.col < 4 ~ 0.5,
                                            id.row == "E" & id.col < 4 ~ 0.25,
                                            id.row == "F" & id.col < 4 ~ 0.125,
                                            id.row == "G" & id.col < 4 ~ 0.0625,
                                            id.row == "H" & id.col < 4 ~ 0),
                            trt = case_when(id.row %in% c("A", "B", "C") & id.col %in% c(4, 5) ~ "ctrl",
                                            (id.row %in% c("D", "E", "F") & id.col %in% c(4, 5)) | 
                                              (id.row %in% c("E", "F", "G") & id.col %in% c(6, 7)) ~ "26",
                                            (id.row %in% c("G", "H") & id.col %in% c(4, 5)) |
                                              (id.row %in% c("A", "H") & id.col %in% c(6, 7)) |
                                              (id.row %in% c("A", "B") & id.col %in% c(8, 9)) ~ "33",
                                            (id.row %in% c("B", "C", "D") & id.col %in% c(6, 7)) |
                                              (id.row %in% c("C", "D", "E") & id.col %in% c(8, 9)) ~ "36"),
                            time = case_when(id.row %in% c("A", "B", "C") & id.col %in% c(4, 5) ~ 0,
                                             (trt %in% c("26", "33") & id.col %in% c(4, 5)) |
                                               id.row %in% c("A", "B", "C", "D") & id.col %in% c(6, 7) ~ 1,
                                             (id.row %in% c("E", "F", "G", "H") & id.col %in% c(6, 7)) |
                                               id.row %in% c("A", "B", "C", "D", "E") & id.col %in% c(8, 9) ~ 2),
                            rep.biol = case_when((id.row %in% c("A", "D", "G") & id.col %in% c(4, 5)) |
                                                   (id.row %in% c("B", "E", "H") & id.col %in% c(6, 7)) |
                                                   (id.row == "C" & id.col %in% c(8, 9)) ~ 1,
                                                 (id.row %in% c("B", "E", "H") & id.col %in% c(4, 5)) |
                                                   (id.row %in% c("C", "F") & id.col %in% c(6, 7)) |
                                                   (id.row %in% c("A", "D") & id.col %in% c(8, 9)) ~ 2,
                                                 (id.row %in% c("C", "F") & id.col %in% c(4, 5)) |
                                                   (id.row %in% c("A", "D", "G") & id.col %in% c(6, 7)) |
                                                   (id.row %in% c("B", "E") & id.col %in% c(8, 9)) ~ 3),
                            rep.tech = case_when(id.col %in% c(1, 4, 6, 8) ~ 1,
                                                 id.col == 3 ~ 3,
                                                 TRUE ~ 2),
                            dil = case_when(type == "unk" ~ 4),
                            id.sample = case_when(type == "std" & sod.cxn >= 0 ~ paste0(type, "-", sod.cxn),
                                                  id %in% c("G08", "G09") ~ "std-no XO",
                                                  id %in% c("F08", "F09") ~ "unk-buffer",
                                                  TRUE ~ paste0(type, "-", trt, "-T", time, "-", rep.biol))
                     )
)

```

```{r calcs}
# subtr blanked plate 
sod <- list_assign(sod, vals = list())

sod <- list_assign(sod, calcs = sod$all %>%
                     mutate(abs.blanked = abs.post - abs.pre, .after = "abs.post") %>%
                     group_by(sod.cxn, type, trt, time, rep.biol, id.sample) %>%
                     summarise(avg.abs = mean(abs.blanked)) %>%
                     ungroup()
                   )

```

## - lin sod rate (sigma aldritch method)

```{r get std curve}
# determining lin sod rate per the sigma kit
# idk if 4pl is needed still

sod$vals <- list_modify(sod$vals, maxabs = as.numeric(sod$calcs[sod$calcs$id.sample == "std-0", "avg.abs"]))

sod <- list_modify(sod, calcs = sod$calcs %>%
                     mutate(sod.linrate = sod$vals$maxabs/avg.abs)
                   )
#temp <- sod  

sod <- list_merge(sod, vals = coef(lm(sod.linrate ~ sod.cxn,
                                       data = filter(sod$calcs, type == "std" & !is.na(sod.cxn)))))


p <- ggplot(filter(sod$calcs, type == "std" & !is.na(sod.cxn)), aes(sod.cxn, sod.linrate)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  labs(y = "linearised SOD activity rate",
       x = "SOD concentration (units/mL)\n(standards)",
       caption = "y = 7.76x + 4.35; R^2 = 0.8591")

p
# good enough

```

```{r calc sod cxn for unks}

sod <- list_modify(sod, calcs = sod$calcs %>%
                     mutate(sod.cxn = case_when(type == "unk" ~ 
                                                  ((sod.linrate - sod$vals[['(Intercept)']])/sod$vals$sod.cxn)*8.5*4, 
                                                TRUE ~ sod.cxn)
                            ))
# unk SOD cxn = [(LSRsample - int) * well volume DF * DF]/slope

p +
  geom_point(filter(sod$calcs, type == "unk"), mapping = aes(col = as.factor(time), shape = trt)) #lmfao

ggplot(filter(sod$calcs, type == "unk" & !is.na(time)), aes(x = sod.cxn, y = sod.linrate,
                                             #shape = as.factor(time), 
                                             #col = trt,
                                             col = as.factor(time)
                                             )) +
  geom_point() +
  facet_wrap(~trt)

# SIGH

```

## - 4pl?

```{r}
# calc inhibition rate % (also from sigma...)

sod <- list_modify(sod, calcs = sod$calcs %>%
                     mutate(sod.inhibrate = (sod$vals$maxabs - avg.abs)/sod$vals$maxabs * 100)
                   )

p <- ggplot(filter(sod$calcs, type == "std"), aes(y = sod.inhibrate, x = log(sod.cxn))) +
  geom_point()

p # this sorta looks like the curve from oxisresearch at least ...

```



