---
title: "260227 LB figs"
date: "2026-02-18"
---

# preamble and loading

figs for LB/committee update


```{r load libs and utils, warning=FALSE}
library(tidyverse)
library(patchwork)
library(survival)
library(survminer)

here::i_am("outputs/2026-02_LB/figs.Rmd")
library(here)

source(here("_ntw/scripts/utils/wrangle.R"))
source(here("_ntw/scripts/utils/analysis.R"))

source(here("_tdt/scripts/utils/wrangle.R"))
```

```{r load data, warning=FALSE}
source(here("_ntw/scripts/R/tidy-dev.R"))
dfs_ntw <- list(
  wide = dfs_tidy$wide,
  long = dfs_tidy$long
) %>%
  lapply(., \(x){
    x %>%
    mutate(across(starts_with("trt"), as.factor))
  })

source(here("_tdt/scripts/R/tidy.R"))
dfs_tdt <- list(
  wide = dfs_tidy$wide,
  long = dfs_tidy$long
) %>%
  lapply(., \(x){
    x %>%
      filter(status %in% c(0, 1)) %>% # drop pmc bugs
      mutate(across(starts_with("trt"), as.factor))
  })

rm(dfs_tidy)
```

# 2x2 results
- pupation big 3

## wrangle

```{r}
# pivot
dfs_ntw1 <- list(
  ss_dev = dfs_ntw$long %>%
    filter(year == 2023,
           pop == "lab" & diet == "LD",
           instar == "pupa",
           is.ntw %in% c(0, 2)) %>% 
    mutate(mass = mass/1000,
           devrate = 1/tt) %>%
    group_by(trt.meanT, trt.flucT) %>% 
    summarise(n = n(),
              avg.mass = mean(mass, na.rm = TRUE),
              se.mass = se(mass),
              avg.devrate = mean(devrate, na.rm = TRUE),
              se.devrate = se(devrate)),
  
  ss_surv = dfs_ntw$wide %>%
    filter(year == 2023,
           pop == "lab" & diet == "LD",
           is.ntw %in% c(0, 2)) %>%
    group_by(trt.meanT, trt.flucT) %>%
    summarise(n.surv = sum(is.pup == 1),
              p.surv = n.surv/sum(is.pup %in% c(0, 1)),
              se.surv = se.prop(p.surv, n.surv))
)
```

## big 3

```{r}
.plotfn <- function(x){
  x %>%
    #filter(trt.flucT == 0) %>%
    ggplot(aes(x = trt.meanT,
               lty = trt.flucT, shape = trt.flucT,
               group = trt.flucT)) +
    geom_point(size = 2) +
    geom_line() +
    geom_errorbar(width = 0.08, lty = "solid",
                  show.legend = FALSE)
}

p1 <- dfs_ntw1$ss_surv %>%
  .plotfn() +
  aes(y = p.surv,
      ymax = p.surv + se.surv,
      ymin = p.surv - se.surv) +
  ylim(c(0, 1)) +
  labs(y = "proportion survived to pupation") 

p2 <- dfs_ntw1$ss_dev %>%
  .plotfn() +
  aes(y = avg.mass,
      ymax = avg.mass + se.mass,
      ymin = avg.mass - se.mass) +
  labs(y = "pupal mass (g)") 

p3 <- dfs_ntw1$ss_dev %>%
  .plotfn() +
  aes(y = avg.devrate,
      ymax = avg.devrate + se.devrate,
      ymin = avg.devrate - se.devrate) +
  labs(y = "development rate (1/days)")

(p1 + p2 + p3) +
  plot_layout(axes = "collect", 
              guides = "collect",
              widths = c(1, 1, 1)
              ) &
  labs(x = "mean temperature (°C)",
       lty = "fluctuation (°C)", shape = "fluctuation (°C)") &
  scale_shape_discrete(labels = c("±0", "±7")) &
  scale_linetype_discrete(labels = c("±0", "±7")) &
  theme_bw() &
  theme(legend.position = "bottom")

```

# ntw results

## wrangle

```{r}
dfs_ntw2 <- list(
  ss_dev = dfs_ntw$long %>%
    FilterForNTWTrts() %>%
    filter(!(pop == "lab" & diet == "TB"),
           instar == "pupa") %>%
    mutate(mass = mass/1000,
           devrate = 1/tt) %>%
    group_by(trt, trt.type, pop) %>%
    summarise(n = n(),
              avg.mass = mean(mass, na.rm = TRUE),
              se.mass = se(mass),
              avg.devrate = mean(devrate, na.rm = TRUE),
              se.devrate = se(devrate)),
  
  ss_surv = dfs_ntw$wide %>%
    FilterForNTWTrts() %>% 
    filter(!(pop == "lab" & diet == "TB"),
           pop != "col",
           is.ntw %in% c(1,2)) %>% 
    group_by(trt, trt.type, pop) %>%
    summarise(n = n(),
              n2 = sum(is.pup %in% c(0, 1)),
              n.surv = sum(is.pup == 1, na.rm = TRUE),
              p.surv = n.surv/sum(is.pup %in% c(0, 1)),
              se.surv = se.prop(p.surv, n.surv))
)
```

## big 3

```{r}
.plotfn <- function(x){
  x %>%
    ggplot(aes(x = trt, lty = pop, shape = pop,
             group = interaction(pop, trt.type))) +
    geom_point(size = 2) +
    geom_line() +
    geom_errorbar(width = 0.1, lty= "solid", show.legend = FALSE) +
    facet_grid(~ trt.type, scales = "free_x", space = "free_x",
               labeller = as_labeller(c(`ctrl` = "control (constant)",
                                        `expt` = "experimental (40 - X)"))
               ) +
    theme_bw() +
    scale_x_discrete(labels = c("260" = "26", "419" = "19", "426" = "26", "433" = "33")) +
    scale_linetype_manual(values = c("field" = "dashed", "lab" = "solid")) +
    scale_shape_manual(values = c("field" = 1, "lab" = 20)) +
    labs(x = "minimum temperature",
         lty = "population", shape = "population")
}

dfs_ntw2$ss_surv %>%
  .plotfn() +
  aes(y = p.surv,
      ymax = p.surv + se.surv,
      ymin = p.surv - se.surv) +
  ylim(c(0, 1)) +
  labs(y = "proportion survived to pupation")

dfs_ntw2$ss_dev %>%
  .plotfn() +
  aes(y = avg.mass,
      ymax = avg.mass + se.mass,
      ymin = avg.mass - se.mass) +
  ylim(c(0, 6.25)) +
  labs(y = "pupal mass (g)") 

dfs_ntw2$ss_dev %>%
  .plotfn() +
  aes(y = avg.devrate,  
      ymax = avg.devrate + se.devrate,
      ymin = avg.devrate - se.devrate) +
  labs(y = "development rate (1/days)")
```




# tdt results

- ctrls survival to 3rd (probably need to use KM curve or sth.. bc 4ths dont even survive to 3rd lol)
- ctrls dev to 4th

## kms

### ctrls + temp
- how control bugs fared

```{r}
km_df <- dfs_tdt$long %>%
  filter(subset == "fromenter" & trt.duration == 0)
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.recover, data = km_df)

ggsurvplot(fit = km_fit, data = km_df) + 
  labs(caption = "from enter")
```


### 40s + recovery duration
- how 0, 24, 48h hot bugs fared

```{r}
# from enter
km_df <- dfs_tdt$long %>%
  filter(subset == "fromenter" & trt.enter == 40)
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.duration, data = km_df)

ggsurvplot(fit = km_fit, data = km_df) + 
  labs(caption = "from enter")
  
# from return
km_df <- dfs_tdt$long %>%
  filter(subset == "fromreturn" & trt.enter == 40)
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.duration, data = km_df)

ggsurvplot(fit = km_fit, data = km_df) +
  labs(caption = "from return")

# another flavor (being ctrl vs expt)
km_df <- dfs_tdt$long %>%
  filter(subset == "fromreturn" & trt.enter == 40)
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.type, data = km_df)

ggsurvplot(fit = km_fit, data = km_df) +
  labs(caption = "from return")

```

### recovery + temp
```{r}
# from enter
km_df <- dfs_tdt$long %>%
  filter(subset == "fromenter" & trt.type == "expt")
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.duration, data = km_df)

ggsurvplot(fit = km_fit, data = km_df,
           facet.by = "trt.recover") + 
  labs(caption = "from enter")
  
# from return
km_df <- dfs_tdt$long %>%
  filter(subset == "fromreturn" & trt.type == "expt")
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.duration, data = km_df)

ggsurvplot(fit = km_fit, data = km_df,
           facet.by = "trt.recover") +
  labs(caption = "from return")
```

### recovery + duration
```{r}
# from enter
km_df <- dfs_tdt$long %>%
  filter(subset == "fromenter" & trt.type == "expt")
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.recover, data = km_df)

ggsurvplot(fit = km_fit, data = km_df,
           facet.by = "trt.duration") + 
  labs(caption = "from enter") +
    scale_color_hue(direction = -1)
  
# from return
km_df <- dfs_tdt$long %>%
  filter(subset == "fromreturn" & trt.type == "expt")
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.recover, data = km_df)

ggsurvplot(fit = km_fit, data = km_df,
           facet.by = "trt.duration") +
  labs(caption = "from return") +
    scale_color_hue(direction = -1)
```