---
title: "tdt viz"
date: "2026-01-06"
---

generate tdt viz

TODO
- before
  - import data
  - import utils
  - make subsets(?)
- analysis
  - all the kms

# preamble

```{r}
# pathfinding
here::i_am("_tdt/scripts/analysis-viz.Rmd")
library(here)

# libs and utils
library(tidyverse)
library(survival) # for Surv 
library(survminer) # for ggsurvplot

source(here("_tdt/scripts/utils/wrangle.R"))
source(here("_tdt/scripts/utils/analysis-viz.R"))
```

```{r data prep}
# import data
source(here("_tdt/scripts/R/tidy.R"))

# format col types for easier plotting...?

# drop pmc bugs
dfs_tidy <- dfs_tidy %>% lapply(., \(x){
  x %>% 
    filter(status %in% c(0, 1)) %>%
    mutate(across(starts_with("trt"), as.factor))
})
```


# kms ctrls

## by rec temp
results
- no major diffs in KMs for 40 ctrls across cohorts

```{r}
# by trt
km_df <- dfs_tidy$long %>%
  filter(subset == "fromenter" & trt.duration == 0)
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.recover, data = km_df)

ggsurvplot(fit = km_fit, data = km_df,
           facet.by = "cohort"
           ) %++%
  AddKMLines(km_df) + 
  scale_color_manual(values = c("#002F70", "#3C6FC4", "#DE738B", "#8E063B")) + 
  labs(caption = "rec duration = 0h")
```

## by cohort
```{r}
# by cohort
km_df <- dfs_tidy$long %>%
  filter(subset == "fromenter" & trt.duration == 0,
         trt.recover == 40)
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ cohort, data = km_df)

ggsurvplot(fit = km_fit, data = km_df,
           #facet.by = "trt.recover"
           ) %++%
  AddKMLines(km_df) +
  labs(caption = "rec 0h @ 40C")

# looking at the 40C grp only -- no major diffs
```


# kms exptal
## by rec temp
```{r}
# from entering
km_df <- dfs_tidy$long %>%
  filter(subset == "fromenter" & trt.enter == 40) # ohh this is where im hitting issues w the subsetting...
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.recover, data = km_df)

ggsurvplot(fit = km_fit, data = km_df,
           #facet.by = "cohort"
           facet.by = "trt.duration"
           ) %++%
  AddKMLines(km_df, dt.recover, 
             trt.duration 
             ) +
  scale_color_manual(values = c("#002F70", "#3C6FC4", "#DE738B", "#8E063B")) +
  labs(caption = "t0 = enter")
```

```{r}
# from return
km_df <- dfs_tidy$long %>%
  filter(subset == "fromreturn" & trt.enter == 40) 
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.recover, data = km_df)

ggsurvplot(fit = km_fit, data = km_df,
           #facet.by = "cohort"
           facet.by = "trt.duration"
           ) %++%
  AddKMLines(km_df, dt.return, 
             trt.duration 
             ) +
  scale_color_manual(values = c("#002F70", "#3C6FC4", "#DE738B", "#8E063B")) +
  labs(caption = "t0 = return to 40C")
```

```{r}
# for STOR consult: differences in surv curves depending on where you start
# km_df <-
#   list(fromenter = dfs_tidy$long %>% filter(trt.enter == 40 & subset == "fromenter"),
#        fromreturn = dfs_tidy$long %>% filter(trt.enter == 40 & subset == "fromreturn"))
km_df <- dfs_tidy$long %>% filter(trt.enter == 40, subset != "fromrecover")
km_fit <- surv_fit(Surv(tt.exit, status) ~ trt.recover, data = km_df)

ggsurvplot_facet(fit = km_fit, data = km_df,
                 facet.by = c("subset", "trt.duration")) +
  AddKMLines(df = filter(km_df, subset == "fromenter"), dt.enter, trt.duration, subset) +
  AddKMLines(df = filter(km_df, subset == "fromreturn"), dt.return, trt.duration, subset) +
  scale_color_manual(values = c("#002F70", "#3C6FC4", "#DE738B", "#8E063B")) +
  labs(caption = "(varying t0)")


```



## by rec dur
```{r}
# effect of trt.duration
km_df <- dfs_tidy$long %>%
  filter(subset == "fromenter" & trt.enter == 40)
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ trt.duration, data = km_df)

ggsurvplot(fit = km_fit, data = km_df,
           facet.by = "cohort"
           #facet.by = "trt.recover"
           ) %++%
  AddKMLines(km_df, dt.recover, cohort
             )
```
## by cohort
```{r}
# effect of cohort
km_df <- dfs_tidy$long %>%
  filter(subset == "fromenter" & trt.enter == 40)
km_fit <- survfit(Surv(km_df$tt.exit, km_df$status) ~ cohort, data = km_df)

ggsurvplot(fit = km_fit, data = km_df,
           #facet.by = "trt.recover",
           facet.by = "trt.duration"
           ) %++%
  AddKMLines(km_df, dt.recover, trt.duration
             )
```




# surv props

## overall
- using simulated 40C data

```{r}
dfs_tidy$widesim %>%
  CalcSurvProps(., trt.recover, trt.duration) %>% 
  ggplot(aes(y = p, x = timept,
             fill = status)) +
  geom_col() +
  facet_grid(trt.duration ~ trt.recover, drop = TRUE) +
  scale_x_discrete(guide = guide_axis(angle = 45))
  

dfs_tidy$widesim %>%
  CalcSurvProps(., trt.recover, trt.duration) %>% 
  #filter(status == "surv") %>%
  ggplot(aes(y = n.initial, x = timept,
             group = interaction(trt.recover, trt.duration),
             )) +
  geom_point() + geom_line() +
  facet_grid(trt.duration ~ trt.recover, drop = TRUE) +
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  labs(caption = "starting N at timepts")
```

