---
title: "2025 ntw dev tidying"
date: "2025-11-26"
---

# # preamble

prepping ntw data for 2025 wrangling

final code is purled to a `.R` script, rerun `purl` step as needed to update the wrangling for analyses

```{r set paths, eval=FALSE, include=FALSE, purl=FALSE}
# run this prior to other pathing stuff if things are breaking
here::i_am("_ntw/scripts/tidy-dev.Rmd")
```

```{r for purling, eval=FALSE, include=FALSE, purl=FALSE}
# rerun this chunk if purled .R script needs to be updated.
# save and apply updates to current .Rmd before purling!

knitr::purl("tidy-dev.Rmd", here::here("_ntw/scripts/R/tidy-dev.R"))

# creates an archive
# knitr::purl("data-tidying.Rmd", 
#             paste0(here::here(bin_paths$y25$ntw), "/archive/cleaning/", 
#                    format(Sys.time(), "%y%m%d-%H%M"), "_tidy-data.R"))
```

# load libs & pkgs

```{r about}
# cleaning/ntw-2025.R

# knitted tidying code for 2025 ntw dev figs/analyses.
# source() this in corresponding analysis scripts.

# this script compiles ntw data from 2023-25 into cohesive units for easier wrangling.
```


```{r load libs}
library(data.table) # for rbindlist
library(tidyverse)
library(here)
```


# # dev data (all yrs)

## loading
```{r load data}
dfs_imported <- list(
  y23 = read.csv(here("_ntw/data/clean/2023/dev.csv"), header = TRUE) %>%
    # dealing w dup ids
    mutate(id = case_when(id == "1379" & !is.na(jdate.pmd) ~ "1379a",
                          expt.group == "A" ~ paste0(id, "a"),
                          TRUE ~ as.character(id))),
    #mutate(id = sprintf("%.1f", id)),
  y24 = read.csv(here("_ntw/data/clean/2024/dev.csv"), header = TRUE),
  y25 = read.csv(here("_ntw/data/clean/2025/dev.csv"), header = TRUE),
  a23 = read.csv(here("_ntw/data/clean/2023/tent-matings.csv"), header = TRUE) %>%
    select(c("id", "trt", "sex", "pop", "id.tent",
             "jdate.ec", "jdate.paired", "jdate.died", "ctrl")) %>%
        filter(!(id %in% c(282, 284))), # bad bugs
  a25 = read.csv(here("_ntw/data/clean/2025/tent-matings.csv"), header = TRUE) %>%
    select(c("id", "trt", "sex", "pop", "cage",
             "jdate.eclosed", "jdate.added", "jdate.removed", 
             "if.fridge", "if.def", "if.culled")) %>%
    filter(is.na(if.culled)) %>% # dont rlly wanna deal w these 2 bugs
    select(-if.culled)
)
```

## standardising

```{r filtering and column cleanup}
dfs_filtered <- list(
  # larva
  ## preremove all MQs
  y23 = dfs_imported[["y23"]] %>%
    filter(is.na(species),
           instar.enter == "hatch" | 
             pop == "field" & instar.enter %in% c("1st", "2nd"),
           pop %in% c("field", "lab"),
           #!(trt %in% c("ctrl", "267", "330")),
           reason.ignore != "lost" | is.na(reason.ignore),
           ) %>%
    rename(#id = ID,
           #jdate.LPI = jdate.LP,
           #trt = treatment,
           cohort = expt.group,
           jdate.long = jdate.surv) %>%
    select(-c(starts_with(c("h.", "if.")), ends_with("2nd"), 
              "instar.enter",  "jdate.collected", "jdate.enter", 
              "jdate.stuck", "jdate.15", "jdate.died",
              "parent.tent", "src", "trt.stage", "grp.trt")),

  y24 = dfs_imported[["y24"]] %>%
    filter(is.na(species),
           instar.enter == "hatch") %>%
    rename(jdate.long = jdate.surv) %>%
    select(-c(ends_with("2nd"), "jdate.enter", "instar.enter", "trt.type")),
  
  y25 = dfs_imported[["y25"]] %>%
    filter(is.na(species),
           !(notes.ignore == "empty") | is.na(notes.ignore)) %>%
    rename(pop = population,
           jdate.long = jdate.surv,
           cage = id.cage) %>%
    select(-c("species", "jdate.enter", "instar.enter", ends_with("2nd"))),
  
  # adults
  a23 = dfs_imported[["a23"]] %>%
    filter(!is.na(jdate.died)) %>% 
    rename(jdate.eclose = jdate.ec,
           jdate.tent = jdate.paired,
           jdate.long = jdate.died,
           trt.ctrl = ctrl,
           cage = id.tent),
  
  a25 = dfs_imported[["a25"]] %>%
    rename(jdate.tent = jdate.added,
           jdate.eclose = jdate.eclosed,
           jdate.long = jdate.removed)
)

```

```{r merging dfs by yr}
# merge adult + larval data
## separate out the col ctrls from the adults alrdy in the larval dev data before merging,
## otherwise coalesce() breaks (missingness is uneven)

dfs_stdised <- list(
  y23 = dfs_filtered[["y23"]] %>% # 716+
    left_join(filter(dfs_filtered[["a23"]], id %in% dfs_filtered$y23$id), 
              by = c("id", "trt", "sex", "pop")) %>%
    mutate(jdate.eclose = coalesce(jdate.eclose.x, jdate.eclose.y),
           jdate.long = coalesce(jdate.long.x, jdate.long.y),
           .keep = "unused") %>% 
    merge(., filter(dfs_filtered[["a23"]], !(id %in% dfs_filtered$y23$id)), 
          all = TRUE) %>%
    mutate(year = 2023),
  
  y24 = dfs_filtered[["y24"]] %>%
    mutate(year = 2024),
  
  y25 = dfs_filtered[["y25"]] %>%   # 752+
    left_join(filter(dfs_filtered[["a25"]], id %in% dfs_filtered$y25$id), 
              by = c("id", "trt", "sex", "pop", "cage")) %>%
    mutate(jdate.eclose = coalesce(jdate.eclose.x, jdate.eclose.y),
           jdate.long = coalesce(jdate.long.x, jdate.long.y),
           .keep = "unused") %>% 
    merge(., filter(dfs_filtered[["a25"]], !(id %in% dfs_filtered$y25$id)), 
          all = TRUE) %>%
    mutate(year = 2025)
  
) %>% lapply(., \(x){
  # stdise column types; fix id #s if text
  x %>%
    mutate(id = case_when(grepl("a$", id) ~ as.numeric(gsub("a", ".1", id)),
                          grepl("-m", id) ~ 3100 + as.numeric(str_sub(id, start = -2)),
                          grepl("-f", id) ~ 3200 + as.numeric(str_sub(id, start = -2)),
                          TRUE ~ as.numeric(id)),
           across(c("id", "trt", starts_with("jdate"), ends_with("T", ignore.case = FALSE)),
                  as.numeric))
})
```

```{r standardising values by yr}
# individual fixes: recoding values + adding missing columns
# stdising date meanings:
  # cull = non-pmd larval death
  # surv = death after eclosion

# 2023: redo trt values, survival coding/notes, sup coding; add trt group
dfs_stdised[["y23"]] <- dfs_stdised[["y23"]] %>% 
  mutate(mass.8th = NA, jdate.8th = NA,
         if.fridge = case_when(is.na(jdate.tent) & jdate.tent - jdate.eclose > 0 ~ "x"), 
         trt = case_when(trt == 337 ~ 426,
                         TRUE ~ trt),
         trt.ctrl = case_when(trt.flucT == 2.5 ~ "diurnal"),
         trt.flucT = case_when(trt == 260 ~ 0, # force diurnals
                               TRUE ~ trt.flucT),
         trt.group = case_when(pop == "lab" & diet == "TB" ~ 1000,
                               pop == "lab" & diet == "LD" ~ 2000,
                               pop == "field" ~ 100),
         fate.dev = case_when(!is.na(jdate.eclose) ~ "ec",
                              !is.na(jdate.pupa) | !is.na(jdate.LPI) ~ "pup",
                              reason.ignore %in% c("wet diet", "accidental", "hot larva", "cut") | 
                                final.fate %in% c("accidental", "culled") ~ "other",
                              !is.na(jdate.pmd) ~ "pmd"),
         jdate.culled = case_when(final.fate %in% c("accidental", "culled") & fate.dev != "pup" ~ as.numeric(jdate.exit))
         ) %>%
  select(-c("final.fate", "reason.ignore"))

# 2024: redo survival coding, trt group
dfs_stdised[["y24"]] <- dfs_stdised[["y24"]] %>% 
  mutate(#jdate.LPI = NA, 
         jdate.exit = NA, 
         trt.group = case_when(id < 1000 ~ 100,
                               id > 2000 ~ 2000,
                               TRUE ~ 1000),
         fate.dev = case_when(!is.na(jdate.eclose) ~ "ec",
                              !is.na(jdate.pupa) ~ "pup",
                              !is.na(jdate.culled) | surv.outcome == 2  ~ "other",
                              !is.na(jdate.pmd) ~ "pmd"),
         jdate.culled = NA,
         jdate.long = case_when(is.na(jdate.eclose) ~ NA_real_,
                                TRUE ~ as.numeric(jdate.long))
         ) %>%
  select(-"surv.outcome")

# 2025: redo survival coding/notes; add timepts, col ctrl info (per 2023)
dfs_stdised[["y25"]] <- dfs_stdised[["y25"]] %>% 
  mutate(fate.dev = case_when(!is.na(jdate.eclose) & !is.na(jdate.long) ~ "ec",
                              !is.na(jdate.pupa) | !is.na(jdate.LPI) ~ "pup",
                              !is.na(jdate.culled) | !is.na(notes.ignore)  ~ "other",
                              !is.na(jdate.pmd) ~ "pmd"),
         jdate.culled = case_when(fate.dev == "other" ~ as.numeric(jdate.culled),
                                  FALSE ~ NA_real_),
         trt.ctrl = case_when(pop == "col" ~ "col")) %>% 
  filter(!is.na(status) | id > 3000) %>%
  select(-c(starts_with("notes"), "status"))
```

```{r standardisng values for all}
# redo: survival, sup coding (counts after reaching 5th)
# fix: exit dates
# add parsing: non-ntw trts, expt vs control
dfs_stdised <- lapply(dfs_stdised, \(x){
  x %>%
    mutate(is.pup = case_when(fate.dev %in% c("ec", "pup") ~ 1,
                                 fate.dev == "pmd" ~ 0,
                                 fate.dev == "other" ~ 2),
           sup = case_when(!is.na(jdate.8th) ~ 8,
                           !is.na(jdate.7th) ~ 7,
                           !is.na(jdate.6th) ~ 6,
                           #!is.na(jdate.5th) ~ 5,
                           #FALSE ~ as.numeric(sup)
                            ),
           is.sup = case_when(!is.na(sup) ~ 1,
                              TRUE ~ 0),
           jdate.exit = case_when(!is.na(jdate.long) ~ as.numeric(jdate.long),
                                  !is.na(jdate.eclose) ~ as.numeric(jdate.eclose),
                                  !is.na(jdate.LPI) ~ as.numeric(jdate.LPI),
                                  !is.na(jdate.pupa) & is.na(jdate.eclose) ~
                                    as.numeric(jdate.pupa + 36), # 15d + 3 wks
                                  !is.na(jdate.culled) ~ as.numeric(jdate.culled),
                                  !is.na(jdate.pmd) ~ as.numeric(jdate.pmd)),
           is.ntw = case_when(trt %in% c(419, 433) ~ 1,
                              trt %in% c(260, 426) ~ 2,
                              TRUE ~ 0),
           trt.type = case_when(trt.maxT == 40 ~ "expt",
                                TRUE ~ "ctrl")
    )
}) #%>% data.table::rbindlist(., fill = TRUE) %>% View()

```

## prep for final export

```{r prep dev data for export}
# combine dfs and remove short-lived larvae
dfs_tidy <- list(
  wide = 
    data.table::rbindlist(dfs_stdised, fill = TRUE) %>%
    filter(jdate.exit - jdate.hatch > 1 | is.na(jdate.hatch) # for some field bugs
    ))


  # TODO could drop jdate column after pivot maybe?
dfs_tidy <- list_modify(dfs_tidy,
                   long = dfs_tidy$wide %>% 
                     mutate(tt.3rd = jdate.3rd - jdate.hatch,
                            tt.4th = jdate.4th - jdate.hatch,
                            tt.5th = jdate.5th - jdate.hatch,
                            tt.6th = jdate.6th - jdate.hatch,
                            tt.7th = jdate.7th - jdate.hatch,
                            tt.8th = jdate.8th - jdate.hatch,
                            tt.wander = jdate.wander - jdate.hatch,
                            tt.pupa = jdate.pupa - jdate.hatch,
                            tt.eclose = jdate.eclose - jdate.pupa,
                            tt.long = jdate.long - jdate.eclose, 
                            tt.fridge = jdate.tent - jdate.eclose
                            #tt.exit = jdate.exit - jdate.hatch
                            ) %>%
                     pivot_longer(cols = starts_with(c("jdate", "mass", "tt")),
                                  names_to = c(".value", "instar"),
                                  values_drop_na = TRUE,
                                  names_pattern = ("([a-z]*\\d*)\\.(\\d*[a-z]*)")) %>%
                     
                     # drop empty dev times but keep masses
                     mutate(tt = case_when(is.na(tt) & !is.na(mass) ~ 999,
                                           TRUE ~ as.numeric(tt))) %>%
                     drop_na(tt) %>%
                     mutate(tt = na_if(tt, 999)) %>%
                     # remove short-lived eclosed bugs
                     filter(!(instar == "long" & tt == 0))
) 
```



# # cleanup
```{r remove intermediate objects}
rm(dfs_imported, dfs_filtered, dfs_stdised)
```

