---
title: "ntw 2025 wrangling"
date: "2025-11-29"
---

# preamble & loading

- data wrangling for ntw 2025 data here
- data gets purled for wrangling later (update script as needed)

```{r set paths, eval=FALSE, purl=FALSE}
# run if things arent working
here::i_am("_ntw/scripts/wrangle-dev.Rmd")
```

```{r purl, eval=FALSE, purl=FALSE}
# rerun to update .R script (save .Rmd first)
knitr::purl("wrangle-dev.Rmd", here::here("_ntw/scripts/R/wrangle-dev.R"))
```

```{r about}
# purled wrangling code for ntw figs.
# compiles 2023-25 development and tent summary statistics.
```

```{r load libs and data, message=FALSE, warning=FALSE}
# libraries, utils
library(tidyverse)
library(here)
source(here("_ntw/scripts/utils/wrangle.R"))

# data
source(here("_ntw/scripts/R/tidy-dev.R"))
```

# util functions

```{r dev ss custom fn}
.CalcDevSS <- function(x){
  x %>%
    mutate(log.mass = log(mass),
           devrate = 1/tt) %>%
    summarise(n = n(),
              avg.logmass = mean(log.mass, na.rm = TRUE),
              se.logmass = se(log.mass),
              avg.mass = mean(mass, na.rm = TRUE),
              se.mass = se(mass),
              avg.tt = mean(tt, na.rm = TRUE),
              se.tt = se(tt),
              avg.devrate = mean(devrate, na.rm = TRUE),
              se.devrate = se(devrate))
}
```

# ss calcs


```{r}
dfs_dev_ss <- list()
```

## development outcomes

```{r overall development}
dfs_dev_ss <- list_modify(
  dfs_dev_ss,
  dev_outcomes_all =
    dfs_tidy$long %>% 
    group_by(across(c(year, pop, diet, starts_with("trt"), instar))) %>%
    .CalcDevSS(),
  
  # groups survivors + culled bugs together
  dev_outcomes_allgrpd =
    dfs_tidy$long %>%
    mutate(is.pup = case_when(is.pup == 2 ~ 1,
                              TRUE ~ as.numeric(is.pup))) %>%
    group_by(across(c(is.pup, year, pop, diet, starts_with("trt"), instar))) %>%
    .CalcDevSS(),
  
  # groups survivors + culled bugs
  # dev_outcomes_nopmd =
  #   dfs_tidy$long %>% 
  #   filter(is.pup != 0 | is.na(is.pup)) %>%
  #   group_by(year, pop, diet, trt, instar) %>%
  #   .CalcDevSS(),
  
  dev_outcomes_allgrpd2 =
    dfs_tidy$long %>%
    # mutate(is.pup = case_when(is.pup == 2 ~ 1,
    #                           TRUE ~ as.numeric(is.pup))) %>%
    group_by(across(c(is.pup, year, pop, diet, starts_with("trt"), instar))) %>%
    .CalcDevSS(),
  
  ad_dev = 
    dfs_tidy$long %>%
    filter(instar %in% c("pupa", "eclose", "surv")) %>%
    group_by(across(c(year, pop, diet, starts_with("trt"), instar))) %>%
    mutate(mass = mass/1000) %>%
    .CalcDevSS(),
  
  ad_dev_bysex = 
    dfs_tidy$long %>%
    filter(instar %in% c("pupa", "eclose", "surv"), !is.na(sex)) %>%
    group_by(across(c(year, pop, diet, starts_with("trt"), instar, sex))) %>%
    mutate(mass = mass/1000) %>%
    .CalcDevSS()
)
```

## survival props

```{r}
dfs_dev_ss <- list_modify(
  dfs_dev_ss,
    surv_outcomes =
    dfs_tidy$wide %>%
    filter(is.pup != 2) %>%
    group_by(across(c(year, pop, diet, starts_with("trt")))) %>%
    summarise(n = n(),
              prop.pup = sum(is.pup == 1)/n,
              se.pup = se.prop(prop.pup, n))
)
```

## sup proportions

```{r supernumerary development}
# TODO maybe a: dfs_wider with TT, pcts, outcomes, etc... sublists? see 2024 ntw wrangle Rmd

dfs_dev_ss <- list_modify(
  dfs_dev_ss,
  sup_outcomes = 
    dfs_tidy$wide %>% 
    filter(is.pup != 2) %>%
    group_by(across(c(year, pop, diet, starts_with("trt")))) %>%
    summarise(N = n(),
              surv_tot = sum(is.pup == 1),
              surv_0th = sum(is.pup == 1 & is.na(sup)),
              surv_6th = sum(is.pup == 1 & sup == 6, na.rm = TRUE),
              surv_7th = sum(is.pup == 1 & sup == 7, na.rm = TRUE),
              surv_8th = sum(is.pup == 1 & sup == 8, na.rm = TRUE),
              died_tot = sum(is.pup == 0),
              died_0th = sum(is.pup == 0 & is.na(sup)),
              died_6th = sum(is.pup == 0 & sup == 6, na.rm = TRUE),
              died_7th = sum(is.pup == 0 & sup == 7, na.rm = TRUE),
              died_8th = sum(is.pup == 0 & sup == 8, na.rm = TRUE),
              ) %>%
      pivot_longer(cols = starts_with(c("surv", "died")),
                 names_to = c("status", ".value"),
                 names_sep = "_") %>%
    mutate(not = N - tot,
           across(c("not", "0th", "6th", "7th", "8th"), ~ ./N, .names = "p_{.col}")) %>%
      rename_with(~ paste0("n_", .x), matches("^(not)|^(\\dth)")) %>%
        pivot_longer(cols = starts_with(c("n_", "p_")),
                 names_to = c(".value", "sup"), names_sep = "_") %>%
    mutate(sup = gsub(sup, pattern = "th", replacement = ""),
           sup = case_when(sup == "not" & status == "surv" ~ "died",
                           sup == "not" & status == "died" ~ "survived",
                           TRUE ~ as.character(sup),
                           ))
)

# nts: for when the names were n_status_stage: 
# names_pattern = "(n_[a-z]*)_(\\d*[a-z]*)")
    
```

# cleanup

```{r cleanup}
rm(dfs_tidy,
   se, se.prop)
```

