---
title: "ntw 2025 tents wrangling"
date: "2025-11-29"
---

# preamble & loading

- data wrangling for ntw 2025 data here
- data gets purled for wrangling later (update script as needed)

```{r set paths, eval=FALSE, purl=FALSE}
# run if things arent working
here::i_am("_ntw/scripts/wrangle-tents.Rmd")
```

```{r purl, eval=FALSE, purl=FALSE}
# rerun to update .R script (save .Rmd first)
knitr::purl("wrangle-tents.Rmd", here::here("_ntw/scripts/R/wrangle-tents.R"))
```

```{r about}
# purled wrangling code for ntw figs.
# compiles 2023-25 development and tent summary statistics.
```

```{r load libs and data, message=FALSE, warning=FALSE}
# libraries, utils
library(tidyverse)
library(here)
source(here("_ntw/scripts/utils/wrangle.R"))

# data
source(here("_ntw/scripts/R/tidy-tents.R"))
```

# util functions
  
```{r eggs ss custom fns}
# counts per cage -- for stats
.CalcTentCounts <- function(x){
  x %>%
  #dfs_tidy$tents %>% # for testing
  group_by(across(c("year", "cage", starts_with(c("mate", "trt", "is"))))) %>%
  summarise(
    # see notes on calc'ing tent duration
    n.f = sum(f.added),
    n.viable = sum(eggs.fert), # (dont rly need?)
    n.coll = sum(eggs.coll),
    n.hatch = sum(eggs.hatched),
    n.coll.perf = n.coll/n.f,
    sqrt.coll.perf = sqrt(n.coll.perf)
  ) %>% 
    #filter(mate.type == "within", mate.pop == "lab", mate.trt == 426) %>% View()
  ungroup() 
}

# counts per cage trt (i.e. per mate type combo) -- for viz
.CalcTentsSS <- function(x){
  x %>%
  #dfs_tidy$tents %>% # for testing
  .CalcTentCounts() %>%
  group_by(across(c("year", starts_with(c("mate", "trt"))))) %>%
  summarise(
    # see notes on calc'ing tent duration
    n.cages.total = n(),
    n.f.total = sum(n.f),
    n.total.coll = sum(n.coll),
    
    # these look rly bad compared to the daily level LOL
    avg.coll.total = mean(n.coll),
    se.coll.total = se(n.coll),
    avg.coll.perf = mean(n.coll.perf),
    se.coll.perf = se(n.coll.perf),
    
    avg.sqrt.coll.perf = mean(sqrt.coll.perf),
    se.sqrt.coll.perf = se(sqrt.coll.perf),
    #p.hatch = n.hatch.total/n.viable.total, 
      # will get prop.hatch per tent if not sum()'d beforehand
    p.hatch = sum(n.hatch)/sum(n.viable), 
    se.hatch = se.prop(p.hatch, sum(n.viable))
            ) %>%
  #filter(mate.type == "within", mate.pop == "lab", mate.trt == 426) %>%
  mutate(across(.cols = everything(), 
                ~ replace(.x, is.nan(.x), NA))) #%>% View()
}
```


# ss calcs

```{r eggs ss calcs}
dfs_tents <- list( #dfs_tents_ss 
  # (for stats)
  ## all tents individually parsed 
  n_pertent = #dfs_pertent_ss
    dfs_tidy$tents %>% 
    .CalcTentCounts(),
  
  # (for viz)
  ## 2025-12-10: have variations on handling colony bugs for now...
  ## treat all col like lab expt bugs
  ss_nocol = dfs_tidy$tents %>% #eggs_nocol
    select(-mate.col) %>% 
    mutate(mate.pop = case_when(mate.pop == "col" ~ "lab",
                                TRUE ~ as.character(mate.pop))) %>% 
    .CalcTentsSS(),
  
  ## treats col like lab expt bugs, but notes which sex was the col
  ss_matecol = dfs_tidy$tents %>% #eggs_matecol
    mutate(mate.pop = case_when(mate.pop == "col" ~ "lab",
                                TRUE ~ as.character(mate.pop)),
           mate.col = na_if(mate.col, "both")) %>%
    .CalcTentsSS(),
  
  ## retains all indicators of col status (population + affected sex)
  ss_allcol = dfs_tidy$tents %>% #eggs_allcol
    .CalcTentsSS()
)
```


# cleanup

```{r cleanup}
rm(dfs_tidy,
   se, se.prop)
```
